import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'uz' | 'ru' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'uz';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

// Translation data
const translations: Record<Language, any> = {
  uz: {
    nav: {
      findPrograms: "Dasturlar",
      universities: "Universitetlar",
      scholarships: "Stipendiyalar",
      careers: "Martabalar",
      getSupport: "Yordam",
      about: "Biz haqimizda",
      contact: "Aloqa",
      blog: "Blog",
      faq: "Savol-javob",
      login: "Kirish",
      signup: "Ro'yxatdan o'tish"
    },
    hero: {
      title: "Xorijdagi Eng Yaxshi Universitetlarni Toping va Ariza Topshiring",
      subtitle: "Oddiy, Tez, Ishonchli — O'zbekistonlik talabalar uchun maxsus",
      findUniversity: "Universitet Topish",
      country: "Mamlakat",
      selectCountry: "Mamlakatni tanlang",
      degree: "Daraja",
      selectDegree: "Darajani tanlang",
      bachelor: "Bakalavr",
      master: "Magistr",
      phd: "PhD",
      field: "Soha",
      selectField: "Sohani tanlang",
      searchPrograms: "Dasturlarni Qidirish",
      quickAccess: "Tezkor Kirish",
      explorePrograms: "Dasturlarni Ko'rish",
      findScholarships: "Stipendiyalar Topish",
      takeCareerQuiz: "Martaba Testini Boshlash"
    },
    values: {
      title: "Nima Uchun StudyPath?",
      personalized: "Shaxsiylashtirilgan Tanlov",
      personalizedDesc: "Sizning maqsad va imkoniyatlaringizga mos dasturlar",
      verified: "Tasdiqlangan Agentliklar",
      verifiedDesc: "Faqat ishonchli hamkorlar bilan ishlang",
      transparent: "Shaffof Narxlar",
      transparentDesc: "Yashirin to'lovlarsiz aniq ma'lumot",
      scholarships: "Stipendiya Markazi",
      scholarshipsDesc: "Minglab grant va stipendiyalarni toping"
    },
    howItWorks: {
      title: "Qanday Ishlaydi",
      step1: "Qidiruv va Filtr",
      step1Desc: "O'zingizga mos dasturlarni toping",
      step2: "Ariza Topshirish",
      step2Desc: "Onlayn ariza shakllari orqali murojaat qiling",
      step3: "Yordam Oling",
      step3Desc: "Maslahatchilar sizga yordam berishadi"
    },
    programs: {
      title: "Universitet Dasturlari",
      subtitle: "Xorijdagi minglab dasturlarni ko'ring",
      search: "Dasturlar yoki universitetlarni qidiring...",
      filters: "Filtrlar",
      studyLevel: "Ta'lim Darajasi",
      allLevels: "Barcha darajalar",
      fieldOfStudy: "Ta'lim Sohasi",
      allFields: "Barcha sohalar",
      tuitionRange: "O'qish Haqi",
      anyRange: "Istalgan narx",
      free: "Bepul",
      results: "natija topildi",
      perYear: "/yil",
      noTuition: "Bepul Ta'lim",
      scholarship: "Stipendiya Mavjud",
      highDemand: "Yuqori Talab",
      matchScore: "Mos Ball",
      deadline: "Muddat",
      viewDetails: "Batafsil",
      save: "Saqlash",
      apply: "Ariza Topshirish",
      askAgency: "Agentlikdan So'rash"
    },
    scholarships: {
      title: "Stipendiyalar",
      subtitle: "Xalqaro grantlar va stipendiyalarni toping",
      search: "Stipendiyalarni qidiring...",
      filters: "Filtrlar",
      results: "natija topildi",
      fullTuition: "To'liq O'qish Haqi",
      partialTuition: "Qisman O'qish Haqi",
      livingStipend: "Yashash Uchun Stipendiya",
      coverage: "Qamrov",
      amount: "Miqdor",
      deadline: "Muddat",
      viewDetails: "Batafsil",
      save: "Saqlash",
      contactCounselor: "Maslahatchi Bilan Aloqa"
    },
    careers: {
      title: "Martaba Yo'riqnomasi",
      subtitle: "O'z kelajagingizni toping va rejalashtiring",
      searchTab: "Martabalarni Qidirish",
      quizTab: "Martaba Testi",
      search: "Martabalarni qidiring...",
      results: "natija topildi",
      salary: "Ish Haqi",
      skills: "Zarur Ko'nikmalar",
      relatedFields: "Tegishli Sohalar",
      pros: "Afzalliklari",
      cons: "Kamchiliklari",
      viewDetails: "Batafsil",
      quizTitle: "O'z Martabangizni Toping",
      quizSubtitle: "Bir necha savolga javob bering, sizga mos martabalarni topamiz",
      question: "Savol",
      next: "Keyingisi",
      previous: "Oldingi",
      seeResults: "Natijalarni Ko'rish",
      recommendedCareers: "Tavsiya Etilgan Martabalar",
      explorePrograms: "Tegishli Dasturlarni Ko'rish"
    },
    programDetail: {
      overview: "Umumiy Ma'lumot",
      requirements: "Talablar",
      deadlines: "Muddatlar",
      costs: "Xarajatlar",
      duration: "Davomiyligi",
      language: "Ta'lim Tili",
      startDate: "Boshlanish Sanasi",
      description: "Tavsif",
      academicRequirements: "Akademik Talablar",
      minimumGPA: "Minimal GPA",
      languageRequirements: "Til Talablari",
      requiredDocuments: "Zarur Hujjatlar",
      intakeDates: "Qabul Muddatlari",
      applicationDeadline: "Ariza Muddati",
      decisionDate: "Qaror Sanasi",
      tuitionFee: "O'qish Haqi",
      applicationFee: "Ariza Haqi",
      visaFee: "Viza Haqi",
      monthlyLiving: "Oylik Yashash Xarajatlari",
      housingAvailability: "Yotoqxona",
      available: "Mavjud",
      notAvailable: "Mavjud emas",
      totalEstimatedCost: "Jami Taxminiy Xarajat",
      firstYear: "Birinchi Yil",
      managedBy: "Boshqaruvchi",
      verifiedAgency: "Tasdiqlangan Agentlik",
      responseTime: "Javob Vaqti",
      hours: "soat",
      requestHelp: "Yordam So'rash",
      apply: "Ariza Topshirish",
      save: "Saqlash",
      urgentDeadline: "Diqqat",
      daysUntilDeadline: "kun qoldi!"
    },
    scholarshipDetail: {
      overview: "Umumiy Ma'lumot",
      eligibility: "Shartlar",
      application: "Ariza Tartibi",
      timeline: "Muddat",
      amount: "Miqdor",
      coverage: "Qamrov",
      tuitionFees: "O'qish Haqi",
      livingExpenses: "Yashash Xarajatlari",
      travelCosts: "Sayohat Xarajatlari",
      healthInsurance: "Tibbiy Sug'urta",
      booksSupplies: "Kitoblar va Materiallar",
      description: "Tavsif",
      requirements: "Talablar",
      benefits: "Imtiyozlar",
      applicationProcess: "Ariza Jarayoni",
      applicationOpen: "Ariza Ochilishi",
      applicationDeadline: "Ariza Muddati",
      resultsAnnounced: "Natijalar E'lon Qilinishi",
      programStarts: "Dastur Boshlanishi",
      apply: "Ariza Topshirish",
      contactCounselor: "Maslahatchi Bilan Aloqa",
      save: "Saqlash",
      urgentDeadline: "Diqqat",
      daysUntilDeadline: "kun qoldi!"
    },
    careerDetail: {
      overview: "Umumiy Ma'lumot",
      salary: "Ish Haqi",
      skills: "Ko'nikmalar",
      education: "Ta'lim",
      outlook: "Istiqbol",
      description: "Tavsif",
      salaryByRegion: "Mintaqalar Bo'yicha Ish Haqi",
      northAmerica: "Shimoliy Amerika",
      europe: "Yevropa",
      asia: "Osiyo",
      middleEast: "Yaqin Sharq",
      requiredSkills: "Zarur Ko'nikmalar",
      educationPath: "Ta'lim Yo'li",
      recommendedDegree: "Tavsiya Etilgan Daraja",
      relevantFields: "Tegishli Sohalar",
      careerOutlook: "Martaba Istiqboli",
      growthRate: "O'sish Sur'ati",
      nextYears: "keyingi 10 yil",
      jobOpenings: "Ish O'rinlari",
      annually: "yiliga",
      careerProgression: "Martaba Rivojlanishi",
      entryLevel: "Boshlang'ich",
      midLevel: "O'rta",
      seniorLevel: "Yuqori",
      years: "yil",
      prosAndCons: "Afzalliklari va Kamchiliklari",
      pros: "Afzalliklari",
      cons: "Kamchiliklari",
      relatedFields: "Tegishli Sohalar",
      topUniversities: "Eng Yaxshi Universitetlar",
      explorePrograms: "Dasturlarni Ko'rish"
    },
    footer: {
      tagline: "Xorijdagi ta'limga yo'lingiz — oddiy va ishonchli",
      contact: "Aloqa",
      email: "Email",
      phone: "Telefon",
      location: "Manzil",
      programs: "Dasturlar",
      universities: "Universitetlar",
      scholarships: "Stipendiyalar",
      careers: "Martabalar",
      about: "Biz Haqimizda",
      aboutUs: "Kompaniya Haqida",
      ourTeam: "Jamoamiz",
      partners: "Hamkorlar",
      news: "Yangiliklar",
      legal: "Huquqiy",
      privacy: "Maxfiylik Siyosati",
      terms: "Foydalanish Shartlari",
      cookies: "Cookie Siyosati",
      allRightsReserved: "Barcha huquqlar himoyalangan"
    },
    notFound: {
      title: "Sahifa Topilmadi",
      message: "Kechirasiz, siz qidirayotgan sahifa mavjud emas.",
      backHome: "Bosh Sahifaga Qaytish"
    }
  },
  ru: {
    nav: {
      findPrograms: "Программы",
      universities: "Университеты",
      scholarships: "Стипендии",
      careers: "Карьера",
      getSupport: "Поддержка",
      about: "О нас",
      contact: "Контакты",
      blog: "Блог",
      faq: "Вопросы",
      login: "Войти",
      signup: "Регистрация"
    },
    hero: {
      title: "Найдите и Поступите в Лучшие Университеты за Рубежом",
      subtitle: "Просто, Быстро, Надёжно — специально для узбекских студентов",
      findUniversity: "Найти Университет",
      country: "Страна",
      selectCountry: "Выберите страну",
      degree: "Степень",
      selectDegree: "Выберите степень",
      bachelor: "Бакалавр",
      master: "Магистр",
      phd: "PhD",
      field: "Область",
      selectField: "Выберите область",
      searchPrograms: "Искать Программы",
      quickAccess: "Быстрый Доступ",
      explorePrograms: "Обзор Программ",
      findScholarships: "Найти Стипендии",
      takeCareerQuiz: "Пройти Тест по Карьере"
    },
    values: {
      title: "Почему StudyPath?",
      personalized: "Персонализированный Подбор",
      personalizedDesc: "Программы, соответствующие вашим целям и возможностям",
      verified: "Проверенные Агентства",
      verifiedDesc: "Работайте только с надёжными партнёрами",
      transparent: "Прозрачные Цены",
      transparentDesc: "Точная информация без скрытых платежей",
      scholarships: "Центр Стипендий",
      scholarshipsDesc: "Найдите тысячи грантов и стипендий"
    },
    howItWorks: {
      title: "Как Это Работает",
      step1: "Поиск и Фильтр",
      step1Desc: "Найдите подходящие программы",
      step2: "Подать Заявку",
      step2Desc: "Подайте заявку через онлайн-формы",
      step3: "Получить Помощь",
      step3Desc: "Консультанты помогут вам"
    },
    programs: {
      title: "Университетские Программы",
      subtitle: "Просмотрите тысячи программ за рубежом",
      search: "Искать программы или университеты...",
      filters: "Фильтры",
      studyLevel: "Уровень Обучения",
      allLevels: "Все уровни",
      fieldOfStudy: "Область Обучения",
      allFields: "Все области",
      tuitionRange: "Стоимость Обучения",
      anyRange: "Любая цена",
      free: "Бесплатно",
      results: "результатов найдено",
      perYear: "/год",
      noTuition: "Бесплатное Обучение",
      scholarship: "Стипендия Доступна",
      highDemand: "Высокий Спрос",
      matchScore: "Соответствие",
      deadline: "Срок",
      viewDetails: "Подробнее",
      save: "Сохранить",
      apply: "Подать Заявку",
      askAgency: "Спросить Агентство"
    },
    scholarships: {
      title: "Стипендии",
      subtitle: "Найдите международные гранты и стипендии",
      search: "Искать стипендии...",
      filters: "Фильтры",
      results: "результатов найдено",
      fullTuition: "Полная Оплата Обучения",
      partialTuition: "Частичная Оплата",
      livingStipend: "Стипендия на Проживание",
      coverage: "Покрытие",
      amount: "Сумма",
      deadline: "Срок",
      viewDetails: "Подробнее",
      save: "Сохранить",
      contactCounselor: "Связаться с Консультантом"
    },
    careers: {
      title: "Карьерный Советник",
      subtitle: "Найдите и спланируйте своё будущее",
      searchTab: "Поиск Карьеры",
      quizTab: "Карьерный Тест",
      search: "Искать карьеры...",
      results: "результатов найдено",
      salary: "Зарплата",
      skills: "Необходимые Навыки",
      relatedFields: "Связанные Области",
      pros: "Преимущества",
      cons: "Недостатки",
      viewDetails: "Подробнее",
      quizTitle: "Найдите Свою Карьеру",
      quizSubtitle: "Ответьте на несколько вопросов, и мы найдём подходящие карьеры",
      question: "Вопрос",
      next: "Далее",
      previous: "Назад",
      seeResults: "Посмотреть Результаты",
      recommendedCareers: "Рекомендуемые Карьеры",
      explorePrograms: "Обзор Связанных Программ"
    },
    programDetail: {
      overview: "Обзор",
      requirements: "Требования",
      deadlines: "Сроки",
      costs: "Расходы",
      duration: "Продолжительность",
      language: "Язык Обучения",
      startDate: "Дата Начала",
      description: "Описание",
      academicRequirements: "Академические Требования",
      minimumGPA: "Минимальный GPA",
      languageRequirements: "Языковые Требования",
      requiredDocuments: "Необходимые Документы",
      intakeDates: "Даты Приёма",
      applicationDeadline: "Срок Подачи Заявки",
      decisionDate: "Дата Решения",
      tuitionFee: "Плата за Обучение",
      applicationFee: "Плата за Заявку",
      visaFee: "Визовый Сбор",
      monthlyLiving: "Ежемесячные Расходы на Проживание",
      housingAvailability: "Общежитие",
      available: "Доступно",
      notAvailable: "Недоступно",
      totalEstimatedCost: "Общая Ориентировочная Стоимость",
      firstYear: "Первый Год",
      managedBy: "Управляется",
      verifiedAgency: "Проверенное Агентство",
      responseTime: "Время Ответа",
      hours: "часов",
      requestHelp: "Запросить Помощь",
      apply: "Подать Заявку",
      save: "Сохранить",
      urgentDeadline: "Внимание",
      daysUntilDeadline: "дней осталось!"
    },
    scholarshipDetail: {
      overview: "Обзор",
      eligibility: "Условия",
      application: "Процесс Подачи",
      timeline: "График",
      amount: "Сумма",
      coverage: "Покрытие",
      tuitionFees: "Плата за Обучение",
      livingExpenses: "Расходы на Проживание",
      travelCosts: "Транспортные Расходы",
      healthInsurance: "Медицинская Страховка",
      booksSupplies: "Книги и Материалы",
      description: "Описание",
      requirements: "Требования",
      benefits: "Преимущества",
      applicationProcess: "Процесс Подачи",
      applicationOpen: "Открытие Заявок",
      applicationDeadline: "Срок Подачи",
      resultsAnnounced: "Объявление Результатов",
      programStarts: "Начало Программы",
      apply: "Подать Заявку",
      contactCounselor: "Связаться с Консультантом",
      save: "Сохранить",
      urgentDeadline: "Внимание",
      daysUntilDeadline: "дней осталось!"
    },
    careerDetail: {
      overview: "Обзор",
      salary: "Зарплата",
      skills: "Навыки",
      education: "Образование",
      outlook: "Перспективы",
      description: "Описание",
      salaryByRegion: "Зарплата по Регионам",
      northAmerica: "Северная Америка",
      europe: "Европа",
      asia: "Азия",
      middleEast: "Ближний Восток",
      requiredSkills: "Необходимые Навыки",
      educationPath: "Путь Образования",
      recommendedDegree: "Рекомендуемая Степень",
      relevantFields: "Связанные Области",
      careerOutlook: "Карьерные Перспективы",
      growthRate: "Темп Роста",
      nextYears: "следующие 10 лет",
      jobOpenings: "Вакансии",
      annually: "ежегодно",
      careerProgression: "Карьерный Рост",
      entryLevel: "Начальный",
      midLevel: "Средний",
      seniorLevel: "Старший",
      years: "лет",
      prosAndCons: "Плюсы и Минусы",
      pros: "Плюсы",
      cons: "Минусы",
      relatedFields: "Связанные Области",
      topUniversities: "Лучшие Университеты",
      explorePrograms: "Обзор Программ"
    },
    footer: {
      tagline: "Ваш путь к образованию за рубежом — просто и надёжно",
      contact: "Контакты",
      email: "Email",
      phone: "Телефон",
      location: "Адрес",
      programs: "Программы",
      universities: "Университеты",
      scholarships: "Стипендии",
      careers: "Карьера",
      about: "О Нас",
      aboutUs: "О Компании",
      ourTeam: "Наша Команда",
      partners: "Партнёры",
      news: "Новости",
      legal: "Правовая Информация",
      privacy: "Политика Конфиденциальности",
      terms: "Условия Использования",
      cookies: "Политика Cookie",
      allRightsReserved: "Все права защищены"
    },
    notFound: {
      title: "Страница не найдена",
      message: "К сожалению, страница, которую вы ищете, не существует.",
      backHome: "Вернуться на Главную"
    }
  },
  en: {
    nav: {
      findPrograms: "Programs",
      universities: "Universities",
      scholarships: "Scholarships",
      careers: "Careers",
      getSupport: "Support",
      about: "About",
      contact: "Contact",
      blog: "Blog",
      faq: "FAQ",
      login: "Log In",
      signup: "Sign Up"
    },
    hero: {
      title: "Find and Apply to Top Universities Abroad",
      subtitle: "Simple, Fast, Trusted — tailored for Uzbek students",
      findUniversity: "Find University",
      country: "Country",
      selectCountry: "Select country",
      degree: "Degree",
      selectDegree: "Select degree",
      bachelor: "Bachelor",
      master: "Master",
      phd: "PhD",
      field: "Field",
      selectField: "Select field",
      searchPrograms: "Search Programs",
      quickAccess: "Quick Access",
      explorePrograms: "Explore Programs",
      findScholarships: "Find Scholarships",
      takeCareerQuiz: "Take Career Quiz"
    },
    values: {
      title: "Why StudyPath?",
      personalized: "Personalized Matches",
      personalizedDesc: "Programs tailored to your goals and abilities",
      verified: "Verified Agencies",
      verifiedDesc: "Work only with trusted partners",
      transparent: "Transparent Costs",
      transparentDesc: "Clear information with no hidden fees",
      scholarships: "Scholarship Hub",
      scholarshipsDesc: "Find thousands of grants and scholarships"
    },
    howItWorks: {
      title: "How It Works",
      step1: "Search & Filter",
      step1Desc: "Find programs that match your needs",
      step2: "Apply",
      step2Desc: "Submit applications through online forms",
      step3: "Get Help",
      step3Desc: "Counselors will assist you"
    },
    programs: {
      title: "University Programs",
      subtitle: "Browse thousands of programs abroad",
      search: "Search programs or universities...",
      filters: "Filters",
      studyLevel: "Study Level",
      allLevels: "All levels",
      fieldOfStudy: "Field of Study",
      allFields: "All fields",
      tuitionRange: "Tuition Range",
      anyRange: "Any price",
      free: "Free",
      results: "results found",
      perYear: "/year",
      noTuition: "No Tuition",
      scholarship: "Scholarship Available",
      highDemand: "High Demand",
      matchScore: "Match Score",
      deadline: "Deadline",
      viewDetails: "View Details",
      save: "Save",
      apply: "Apply",
      askAgency: "Ask Agency"
    },
    scholarships: {
      title: "Scholarships",
      subtitle: "Find international grants and scholarships",
      search: "Search scholarships...",
      filters: "Filters",
      results: "results found",
      fullTuition: "Full Tuition",
      partialTuition: "Partial Tuition",
      livingStipend: "Living Stipend",
      coverage: "Coverage",
      amount: "Amount",
      deadline: "Deadline",
      viewDetails: "View Details",
      save: "Save",
      contactCounselor: "Contact Counselor"
    },
    careers: {
      title: "Career Advisor",
      subtitle: "Discover and plan your future",
      searchTab: "Search Careers",
      quizTab: "Career Quiz",
      search: "Search careers...",
      results: "results found",
      salary: "Salary",
      skills: "Required Skills",
      relatedFields: "Related Fields",
      pros: "Pros",
      cons: "Cons",
      viewDetails: "View Details",
      quizTitle: "Find Your Career",
      quizSubtitle: "Answer a few questions and we'll find matching careers",
      question: "Question",
      next: "Next",
      previous: "Previous",
      seeResults: "See Results",
      recommendedCareers: "Recommended Careers",
      explorePrograms: "Explore Related Programs"
    },
    programDetail: {
      overview: "Overview",
      requirements: "Requirements",
      deadlines: "Deadlines",
      costs: "Costs",
      duration: "Duration",
      language: "Language of Instruction",
      startDate: "Start Date",
      description: "Description",
      academicRequirements: "Academic Requirements",
      minimumGPA: "Minimum GPA",
      languageRequirements: "Language Requirements",
      requiredDocuments: "Required Documents",
      intakeDates: "Intake Dates",
      applicationDeadline: "Application Deadline",
      decisionDate: "Decision Date",
      tuitionFee: "Tuition Fee",
      applicationFee: "Application Fee",
      visaFee: "Visa Fee",
      monthlyLiving: "Monthly Living Costs",
      housingAvailability: "Housing",
      available: "Available",
      notAvailable: "Not Available",
      totalEstimatedCost: "Total Estimated Cost",
      firstYear: "First Year",
      managedBy: "Managed By",
      verifiedAgency: "Verified Agency",
      responseTime: "Response Time",
      hours: "hours",
      requestHelp: "Request Help",
      apply: "Apply",
      save: "Save",
      urgentDeadline: "Attention",
      daysUntilDeadline: "days left!"
    },
    scholarshipDetail: {
      overview: "Overview",
      eligibility: "Eligibility",
      application: "Application",
      timeline: "Timeline",
      amount: "Amount",
      coverage: "Coverage",
      tuitionFees: "Tuition Fees",
      livingExpenses: "Living Expenses",
      travelCosts: "Travel Costs",
      healthInsurance: "Health Insurance",
      booksSupplies: "Books & Supplies",
      description: "Description",
      requirements: "Requirements",
      benefits: "Benefits",
      applicationProcess: "Application Process",
      applicationOpen: "Application Opens",
      applicationDeadline: "Application Deadline",
      resultsAnnounced: "Results Announced",
      programStarts: "Program Starts",
      apply: "Apply",
      contactCounselor: "Contact Counselor",
      save: "Save",
      urgentDeadline: "Attention",
      daysUntilDeadline: "days left!"
    },
    careerDetail: {
      overview: "Overview",
      salary: "Salary",
      skills: "Skills",
      education: "Education",
      outlook: "Outlook",
      description: "Description",
      salaryByRegion: "Salary by Region",
      northAmerica: "North America",
      europe: "Europe",
      asia: "Asia",
      middleEast: "Middle East",
      requiredSkills: "Required Skills",
      educationPath: "Education Path",
      recommendedDegree: "Recommended Degree",
      relevantFields: "Relevant Fields",
      careerOutlook: "Career Outlook",
      growthRate: "Growth Rate",
      nextYears: "next 10 years",
      jobOpenings: "Job Openings",
      annually: "annually",
      careerProgression: "Career Progression",
      entryLevel: "Entry Level",
      midLevel: "Mid Level",
      seniorLevel: "Senior Level",
      years: "years",
      prosAndCons: "Pros & Cons",
      pros: "Pros",
      cons: "Cons",
      relatedFields: "Related Fields",
      topUniversities: "Top Universities",
      explorePrograms: "Explore Programs"
    },
    footer: {
      tagline: "Your path to education abroad — simple and reliable",
      contact: "Contact",
      email: "Email",
      phone: "Phone",
      location: "Location",
      programs: "Programs",
      universities: "Universities",
      scholarships: "Scholarships",
      careers: "Careers",
      about: "About",
      aboutUs: "About Us",
      ourTeam: "Our Team",
      partners: "Partners",
      news: "News",
      legal: "Legal",
      privacy: "Privacy Policy",
      terms: "Terms of Service",
      cookies: "Cookie Policy",
      allRightsReserved: "All rights reserved"
    },
    notFound: {
      title: "Page Not Found",
      message: "Sorry, the page you are looking for does not exist.",
      backHome: "Back to Home"
    }
  }
};
