import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'uz' | 'ru' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'uz';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    
    // Try current language
    let value: any = translations[language];
    for (const k of keys) {
      value = value?.[k];
    }
    
    // If found and it's a string, return it
    if (typeof value === 'string') return value;
    
    // Fallback to Russian
    if (language !== 'ru') {
      value = translations['ru'];
      for (const k of keys) {
        value = value?.[k];
      }
      if (typeof value === 'string') return value;
    }
    
    // Fallback to English
    if (language !== 'en') {
      value = translations['en'];
      for (const k of keys) {
        value = value?.[k];
      }
      if (typeof value === 'string') return value;
    }
    
    // Log missing key in development
    if (process.env.NODE_ENV === 'development') {
      console.warn(`Missing translation key: ${key}`);
    }
    
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

// Translation data
const translations: Record<Language, any> = {
  uz: {
    nav: {
      home: "Bosh sahifa",
      findPrograms: "Dasturlar",
      universities: "Universitetlar",
      scholarships: "Stipendiyalar",
      careers: "Martabalar",
      getSupport: "Yordam",
      about: "Biz haqimizda",
      contact: "Aloqa",
      blog: "Blog",
      faq: "Savol-javob",
      login: "Kirish",
      signup: "Ro'yxatdan o'tish"
    },
    common: {
      all: "Barchasi",
      error: "Xato",
      search: "Qidirish",
      filters: "Filtrlar",
      results: "Natijalar",
      viewDetails: "Batafsil Ko'rish",
      apply: "Ariza Topshirish",
      contactCounselor: "Maslahatchi Bilan Bog'lanish",
      learnMore: "Batafsil",
      back: "Ortga",
      next: "Keyingi",
      previous: "Oldingi",
      save: "Saqlash",
      cancel: "Bekor Qilish",
      completed: "Bajarildi",
      pending: "Kutilmoqda",
      whatNext: "Keyingi Qadamlar",
      country: "Mamlakat",
      field: "Soha",
      degree: "Daraja",
      coverage: "Qamrov",
      amount: "Miqdor",
      deadline: "Muddat",
      open: "Ochiladi",
      resultsAnnounced: "Natijalar e'lon qilinadi",
      timeline: "Vaqt Jadvali",
      noResultsTitle: "Hech narsa topilmadi",
      noResultsSubtitle: "Iltimos, qidiruv shartlaringizni o'zgartiring",
      searchPlaceholder: "Qidirish...",
      loading: "Yuklanmoqda...",
      saving: "Saqlanmoqda...",
      university: "Universitet",
      program: "Dastur"
    },
    months: {
      jan: "Yan",
      feb: "Fev",
      mar: "Mar",
      apr: "Apr",
      may: "May",
      jun: "Iyun",
      jul: "Iyul",
      aug: "Avg",
      sep: "Sen",
      oct: "Okt",
      nov: "Noy",
      dec: "Dek"
    },
    hero: {
      title: "Xorijdagi Eng Yaxshi Universitetlarni Toping va Ariza Topshiring",
      subtitle: "Oddiy, Tez, Ishonchli — O'zbekistonlik talabalar uchun maxsus",
      searchTitle: "Universitet qidiruvingizni boshlang",
      findUniversity: "Universitet Topish",
      country: "Mamlakat",
      selectCountry: "Mamlakatni tanlang",
      degree: "Daraja",
      selectDegree: "Darajani tanlang",
      chooseDegree: "Darajani tanlang",
      bachelor: "Bakalavr",
      master: "Magistr",
      phd: "PhD",
      field: "Soha",
      selectField: "Sohani tanlang",
      searchPrograms: "Dasturlarni Qidirish",
      searchButton: "Dasturlarni Qidirish",
      quickAccess: "Tezkor Kirish",
      explorePrograms: "Dasturlarni Ko'rish",
      findScholarships: "Stipendiyalar Topish",
      takeCareerQuiz: "Martaba Testini Boshlash"
    },
    values: {
      title: "Nima Uchun StudyPath?",
      personalized: "Shaxsiylashtirilgan Tanlov",
      personalizedDesc: "Sizning maqsad va imkoniyatlaringizga mos dasturlar",
      verified: "Tasdiqlangan Agentliklar",
      verifiedDesc: "Faqat ishonchli hamkorlar bilan ishlang",
      transparent: "Shaffof Narxlar",
      transparentDesc: "Yashirin to'lovlarsiz aniq ma'lumot",
      scholarships: "Stipendiya Markazi",
      scholarshipsDesc: "Minglab grant va stipendiyalarni toping"
    },
    whyChoose: {
      title: "Nima Uchun StudyPath?",
      personalizedMatches: "Shaxsiylashtirilgan Mosliklar",
      personalizedMatchesDesc: "Sizning maqsadlaringizga, ballaringizga va byudjetingizga mos keluvchi dasturlarni toping",
      trustedSupport: "Ishonchli Yordam",
      trustedSupportDesc: "Tasdiqlangan agentliklar va maslahatchilar orqali professional yo'llanma",
      timeSaving: "Vaqtni Tejash",
      timeSavingDesc: "Minglab dasturlarni bir joyda solishtiring va onlayn ariza topshiring",
      informedDecisions: "Ma'lumotli Qarorlar",
      informedDecisionsDesc: "Batafsil ma'lumotlar va sharhlar orqali to'g'ri tanlov qiling"
    },
    howItWorks: {
      title: "Qanday Ishlaydi",
      step1: "Qidiruv va Filtr",
      step1Desc: "O'zingizga mos dasturlarni toping",
      step2: "Ariza Topshirish",
      step2Desc: "Onlayn ariza shakllari orqali murojaat qiling",
      step3: "Yordam Oling",
      step3Desc: "Maslahatchilar sizga yordam berishadi"
    },
    cta: {
      title: "Sayohatingizni Boshlashga Tayyormisiz?",
      description: "Minglab dasturlarni ko'rib chiqing va o'zingizga eng mos universitetni toping",
      button: "Dasturlarni Ko'rish"
    },
    programs: {
      title: "Universitet Dasturlari",
      subtitle: "Xorijdagi minglab dasturlarni ko'ring",
      pageTitle: "Universitet Dasturlari",
      pageDescription: "Xorijdagi minglab dasturlarni ko'ring va o'zingizga mos ta'lim toping",
      search: "Dasturlar yoki universitetlarni qidiring...",
      searchPlaceholder: "Dasturlar yoki universitetlarni qidiring...",
      filters: "Filtrlar",
      studyLevel: "Ta'lim Darajasi",
      allLevels: "Barcha darajalar",
      fieldOfStudy: "Ta'lim Sohasi",
      allFields: "Barcha sohalar",
      country: "Mamlakat",
      tuitionRange: "O'qish Haqi",
      anyRange: "Istalgan narx",
      free: "Bepul",
      showing: "Ko'rsatilmoqda",
      programs: "dastur",
      results: "natija topildi",
      perYear: "/yil",
      noTuition: "Bepul Ta'lim",
      scholarship: "Stipendiya Mavjud",
      scholarshipAvailable: "Stipendiya Mavjud",
      highDemand: "Yuqori Talab",
      matchScore: "Mos Ball",
      deadline: "Muddat",
      viewDetails: "Batafsil",
      save: "Saqlash",
      apply: "Ariza Topshirish",
      askAgency: "Agentlikdan So'rash"
    },
    universities: {
      pageTitle: "Universitetlar",
      pageDescription: "Mamlakatlar bo'yicha universitetlar va dasturlarni ko'ring",
      selectCountry: "Mamlakatni tanlang",
      allCountries: "Barcha mamlakatlar",
      countryOverview: "Mamlakat Haqida",
      tuitionRange: "O'qish Haqi Oralig'i",
      livingCost: "Yashash Xarajatlari",
      visaRequirement: "Viza Talablari",
      programsAvailable: "Mavjud Dasturlar",
      filterByDegree: "Daraja bo'yicha",
      filterByField: "Soha bo'yicha",
      filterByTuition: "Narx bo'yicha",
      filterByDeadline: "Muddat bo'yicha",
      requirements: "Talablar",
      intakeDates: "Qabul Muddatlari",
      applicationDeadline: "Ariza Muddati",
      viewProgram: "Dasturni Ko'rish",
      applyNow: "Hozir Ariza Topshirish",
      perMonth: "/oy",
      perYear: "/yil",
      requiredVisa: "Viza Kerak",
      countries: {
        turkey: "Turkiya",
        malaysia: "Malayziya",
        qatar: "Qatar",
        saudiArabia: "Saudiya Arabistoni",
        australia: "Avstraliya",
        uk: "Buyuk Britaniya",
        canada: "Kanada",
        germany: "Germaniya",
        usa: "AQSh",
        poland: "Polsha"
      }
    },
    scholarships: {
      title: "Stipendiyalar",
      subtitle: "Xalqaro grantlar va stipendiyalarni toping",
      pageTitle: "Xalqaro Stipendiyalar",
      pageDescription: "Dunyoning eng yaxshi universitetlarida o'qish uchun grantlar va stipendiyalarni toping",
      searchPlaceholder: "Stipendiyalarni qidiring...",
      search: "Stipendiyalarni qidiring...",
      filters: "Filtrlar",
      filterCountry: "Mamlakat",
      filterField: "Soha",
      filterDegree: "Daraja",
      filterCoverage: "Qamrov",
      filterDeadline: "Muddat",
      deadlineFilter: {
        all: "Barcha muddatlar",
        upcoming: "Yaqinlashayotgan (30 kun)",
        thisMonth: "Shu oyda",
        next3Months: "Keyingi 3 oyda",
      },
      results: "natija topildi",
      fullTuition: "To'liq O'qish Haqi",
      partialTuition: "Qisman O'qish Haqi",
      livingStipend: "Yashash Uchun Stipendiya",
      fullCoverage: "To'liq Qamrov",
      partialCoverage: "Qisman Qamrov",
      coverage: "Qamrov",
      amount: "Miqdor",
      deadline: "Muddat",
      organization: "Tashkilot",
      degreeLevel: "Daraja",
      viewDetails: "Batafsil",
      apply: "Ariza Topshirish",
      applyOnOfficialSite: "Rasmiy saytda ariza topshirish",
      save: "Saqlash",
      contactCounselor: "Maslahatchi Bilan Aloqa",
      noResultsTitle: "Hech narsa topilmadi",
      noResultsSubtitle: "Iltimos, qidiruv shartlaringizni o'zgartiring",
      daysLeft: "kun qoldi",
      closed: "Yopilgan",
      lastDay: "Ariza topshirishning oxirgi kuni!",
      applicationClosesOn: "Ariza qabul qilish tugaydi",
      applicationClosed: "Ushbu grant arizasi yopildi.",
      infoOutdated: "Ma'lumot eskirgan bo'lishi mumkin",
      infoNotRecentlyUpdated: "Ushbu grant ma'lumoti 90 kundan ortiq vaqt davomida yangilanmagan. Iltimos, rasmiy saytda tafsilotlarni tekshiring.",
      coverageDetails: "Qamrov tafsilotlari",
      tuitionCoverage: "O'qish to'lovi qamrovi",
      travelAllowance: "Sayohat xarajatlari",
      insuranceCoverage: "Sug'urta qamrovi",
      otherBenefits: "Boshqa imtiyozlar",
      requiredDocuments: "Kerakli hujjatlar",
      commonMistakes: "Keng tarqalgan xatolar",
      trustSignals: "Ishonch va tasdiqlash",
      verifiedScholarship: "Tasdiqlangan grant",
      officialWebsite: "Rasmiy veb-sayt",
      relatedPrograms: "Bog'liq dasturlar",
      relatedCareers: "Bog'liq kasblar",
      faq: "Ko'p beriladigan savollar",
      externalRedirectTitle: "Platformamizni tark etyapsiz",
      externalRedirectMessage: "Siz platformamizni tark etyapsiz va to'g'ridan-to'g'ri rasmiy grant veb-saytida ariza topshirasiz. Biz ariza jarayoni yoki natijalar uchun javobgar emasmiz.",
      agreeAndContinue: "Men tushundim va davom etishga roziman",
      continueToApplication: "Arizaga o'tish",
      lastUpdated: "Oxirgi yangilanish",
      languageRequirements: "Til talablari",
      gpaRequirement: "Minimal o'rtacha ball",
      nationalityRestrictions: "Fuqarolik talablari",
      eligibility: "Talablar",
      benefits: "Imtiyozlar",
      applicationProcess: "Ariza jarayoni",
      timeline: "Vaqt jadvali",
      keyInfo: "Asosiy ma'lumot",
    },
    partners: {
      title: "Bizning Hamkorlarimiz",
      subtitle: "Tasdiqlangan va akkreditatsiyalangan institutlar",
      verified: "Tasdiqlangan",
      accredited: "Akkreditatsiyalangan",
      scholarships: "Stipendiyalar",
      placement: "Joylashtirish",
      support: "24/7 Yordam"
    },
    apply: {
      title: "Ariza Topshirish",
      subtitle: "Xorijdagi universitet dasturlariga ariza topshiring",
      applicationForm: "Ariza Formasi",
      applyingTo: "Ariza Topshirilmoqda",
      degreeLevel: "Daraja",
      yourCompletedEducation: "Sizning Eng Yuqori Ta'limingiz",
      completedEducationHelp: "Sizning hozirgi ta'lim darajangiz (ariza topshiryotgan dastur emas)",
      profile: "Profil",
      eligibility: "Moslik",
      documents: "Hujjatlar",
      review: "Ko'rib chiqish",
      confirmation: "Tasdiqlash",
      personalDetails: "Shaxsiy Ma'lumotlar",
      academicInfo: "Ta'lim Ma'lumotlari (Ixtiyoriy)",
      academicInfoOptional: "Ta'lim Ma'lumotlari (Ixtiyoriy)",
      reviewSubmit: "Ko'rib Chiqish va Yuborish",
      optional: "ixtiyoriy",
      fieldRequired: "Bu maydon to'ldirilishi shart",
      selectProgramFirst: "Iltimos, avval dasturni tanlang",
      eligibilityOptionalNote: "Ushbu ma'lumotlar ixtiyoriy, lekin to'ldirilsa dastur mosligini aniqlashga yordam beradi",
      documentsOptionalNote: "Hujjatlar ixtiyoriy, lekin ularni yuklash arizangizni tezlashtiradi",
      nationality: "Millati",
      selectNationality: "Millatni tanlang",
      currentCity: "Hozirgi Shahar",
      firstNamePlaceholder: "Ismingizni kiriting",
      lastNamePlaceholder: "Familiyangizni kiriting",
      emailPlaceholder: "pochta@example.com",
      phonePlaceholder: "+998 XX XXX XX XX",
      fullName: "To'liq Ism",
      programDetails: "Dastur Taqsimoti",
      university: "Universitet",
      program: "Dastur",
      education: "Ta'lim",
      highestQualification: "Eng Yuqori Malaka",
      selectQualification: "Malakani tanlang",
      highSchool: "O'rta Maktab",
      bachelor: "Bakalavr",
      master: "Magistr",
      phd: "PhD",
      bachelorOfScience: "Bakalavr (Fan)",
      masterOfScience: "Magistr (Fan)",
      doctorOfPhilosophy: "Doktor (PhD)",
      selectTest: "Testni tanlang",
      notTaken: "Hali topshirmagan",
      score: "Ball",
      budgetRange: "Byudjet Oralig'i",
      selectBudget: "Byudjetni tanlang",
      scholarshipInterest: "Stipendiyaga qiziqaman",
      transcript: "Transcript",
      englishProof: "Ingliz Tili Sertifikati",
      passport: "Pasport",
      cv: "CV / Rezyume",
      recommendationLetters: "Tavsiya Xatlari",
      uploadFile: "Fayl Yuklash",
      invalidFileType: "Noto'g'ri fayl turi",
      fileTooLarge: "Fayl juda katta (Maksimal 5MB)",
      documentsSupportedFormats: "Qo'llab-quvvatlanadigan formatlar",
      consentText: "Men o'z ma'lumotlarimni agentlik bilan bo'lishishga roziman va ariza shartlariga roziman",
      consentRequired: "Davom etish uchun rozilik kerak",
      readyToSubmit: "Ariza yuborishga tayyor!",
      applicationSubmitted: "Ariza Muvaffaqiyatli Yuborildi!",
      submittedMessage: "Arizangiz qabul qilindi. Agentlik tez orada siz bilan bog'lanadi.",
      applicationId: "Ariza ID",
      responseTime: "Javob Vaqti",
      whatNext: "Keyingi Qadamlar",
      whatNext1: "Siz elektron pochtangizga tasdiqlash xatini olasiz",
      whatNext2: "Bizning agentligimiz 48 soat ichida siz bilan bog'lanadi",
      whatNext3: "Ular sizga qo'shimcha hujjatlar va keyingi qadamlar haqida ma'lumot beradi",
      returnHome: "Bosh Sahifaga Qaytish",
      back: "Orqaga",
      next: "Keyingisi",
      submitting: "Yuborilmoqda...",
      submit: "Ariza Yuborish",
      success: "Muvaffaqiyat",
      applicationSubmittedSuccess: "Arizangiz muvaffaqiyatli yuborildi",
      submissionError: "Arizani yuborishda xatolik yuz berdi",
      invalidEmail: "To'g'ri elektron pochta manzilini kiriting",
      invalidPhone: "To'g'ri telefon raqamini kiriting"
    },
    requestHelp: {
      title: "Ariza bo'yicha yordam so'rash",
      subtitle: "Jamoamiz 24-48 soat ichida siz bilan bog'lanadi",
      fullName: "To'liq ism",
      email: "Email manzil",
      phone: "Telefon raqami (ixtiyoriy)",
      helpType: "Sizga nima kerak?",
      helpTypes: {
        eligibility: "Muvofiqlik savollari",
        documents: "Hujjat talablari",
        application: "Ariza jarayoni",
        general: "Umumiy so'rov"
      },
      educationLevel: "Joriy ta'lim darajasi",
      educationLevels: {
        highSchool: "O'rta maktab",
        bachelor: "Bakalavr darajasi",
        master: "Magistr darajasi"
      },
      message: "Savolingiz yoki tashvishingizni tasvirlab bering",
      messagePlaceholder: "Sizga qanday yordam kerakligi haqida batafsil ma'lumot bering...",
      contactMethod: "Afzal qilingan aloqa usuli",
      contactMethods: {
        email: "Email",
        phone: "Telefon qo'ng'irog'i",
        whatsapp: "WhatsApp"
      },
      submit: "So'rov yuborish",
      cancel: "Bekor qilish",
      successTitle: "So'rov yuborildi!",
      successMessage: "Jamoamiz 24-48 soat ichida sizning afzal usul orqali bog'lanadi.",
      loginRequired: "Yordam so'rash uchun tizimga kiring",
      loginButton: "Kirish"
    },
    savedPrograms: {
      title: "Saqlangan dasturlar",
      empty: "Siz hali hech qanday dastur saqlamadingiz",
      emptyDescription: "Dasturlarni ko'rib chiqing va bu yerga qo'shish uchun 'Dasturni saqlash' tugmasini bosing",
      browsePrograms: "Dasturlarni ko'rish",
      saved: "Saqlangan",
      saveProgram: "Dasturni saqlash",
      unsave: "O'chirish",
      addNote: "Izoh qo'shish",
      notePlaceholder: "Bu dastur haqida shaxsiy izohlar qo'shing...",
      compareSelected: "Tanlanganni solishtirish",
      selectToCompare: "Solishtirish uchun 2+ dasturni tanlang",
      loginToSave: "Dasturlarni saqlash uchun tizimga kiring",
      savedSuccess: "Dastur muvaffaqiyatli saqlandi",
      unsavedSuccess: "Dastur saqlangan ro'yxatdan o'chirildi",
      compare: {
        title: "Dasturlarni solishtirish",
        backToSaved: "Saqlangan dasturlarga qaytish",
        university: "Universitet",
        program: "Dastur",
        country: "Mamlakat",
        degree: "Daraja",
        field: "O'quv sohasi",
        tuition: "To'lov",
        applicationFee: "Ariza to'lovi",
        duration: "Davomiyligi",
        housing: "Yashash joyi mavjud",
        requirements: "Talablar",
        deadlines: "Ariza muddatlari",
        applyNow: "Hozir ariza topshirish"
      }
    },
    agencyDashboard: {
      title: "Agentlik Boshqaruv Paneli",
      subtitle: "Yordam so'rovlarini boshqarish va talabalar bilan ishlash",
      totalRequests: "Jami So'rovlar",
      allRequests: "Barcha so'rovlar",
      pending: "Kutilmoqda",
      needsResponse: "Javob kerak",
      inProgress: "Jarayonda",
      activeWork: "Faol ish",
      resolved: "Hal Qilindi",
      completed: "Bajarildi",
      filters: "Filtrlar",
      searchPlaceholder: "Ism, email, universitet yoki dastur bo'yicha qidiring...",
      allStatuses: "Barcha holatlar",
      statusPending: "Kutilmoqda",
      statusInProgress: "Jarayonda",
      statusResolved: "Hal Qilindi",
      statusClosed: "Yopildi",
      helpRequests: "Yordam So'rovlari",
      helpRequestsDescription: "Talabalarga yordam berish uchun barcha so'rovlarni boshqaring",
      viewDetails: "Batafsil",
      noRequests: "So'rovlar topilmadi",
      noRequestsDescription: "Hozircha yordam so'rovlari yo'q",
      requestDetails: "So'rov Tafsilotlari",
      requestDetailsDescription: "To'liq ma'lumot va holat yangilanishlari",
      studentInfo: "Talaba Ma'lumotlari",
      programInfo: "Dastur Ma'lumotlari",
      studentMessage: "Talaba Xabari",
      updateStatus: "Holatni Yangilash",
      agencyNotes: "Agentlik Izohlari",
      agencyNotesPlaceholder: "Bu so'rov haqida ichki izohlarni kiriting...",
      createdAt: "Yaratilgan",
      updatedAt: "Yangilangan",
      saveChanges: "O'zgarishlarni Saqlash",
      updateSuccess: "So'rov muvaffaqiyatli yangilandi",
      updateError: "So'rovni yangilashda xatolik yuz berdi"
    },
    careers: {
      title: "Martaba Yo'riqnomasi",
      subtitle: "O'z kelajagingizni toping va rejalashtiring",
      pageTitle: "Martaba Maslahati",
      pageDescription: "O'z kelajagingizni rejalashtiring va eng mos martaba yo'lini toping",
      searchTab: "Martabalarni Qidirish",
      quizTab: "Martaba Testi",
      searchPlaceholder: "Martabalarni qidiring...",
      search: "Martabalarni qidiring...",
      results: "natija topildi",
      salary: "Ish Haqi",
      growth: "O'sish",
      demand: "Talab",
      demandVeryHigh: "Juda Yuqori",
      demandHigh: "Yuqori",
      demandModerate: "O'rtacha",
      skills: "Zarur Ko'nikmalar",
      relatedFields: "Tegishli Sohalar",
      topUniversities: "Eng Yaxshi Universitetlar",
      pros: "Afzalliklari",
      cons: "Kamchiliklari",
      viewDetails: "Batafsil",
      learnMore: "Batafsil",
      explorePrograms: "Dasturlarni Ko'rish",
      question: "Savol",
      next: "Keyingisi",
      previous: "Oldingi",
      seeResults: "Natijalarni Ko'rish",
      recommendedCareers: "Tavsiya Etilgan Martabalar",
      quiz: {
        title: "Holland RIASEC Martaba Testi",
        subtitle: "12 ta savolga javob bering va sizga mos martabalarni toping",
        resultsTitle: "Sizning Natijalaringiz!",
        resultsSubtitle: "Holland Kodi asosida sizga mos martabalar",
        yourType: "Sizning Turingiz",
        personalityProfile: "Shaxsiyat Profili",
        primary: "Asosiy",
        match: "moslik",
        retake: "Qayta Topshirish",
        score: "Ball",
        saveResults: "Natijalarni Saqlash",
        saved: "Saqlandi",
        saveSuccess: "Natijalaringiz muvaffaqiyatli saqlandi",
        saveError: "Natijalarni saqlashda xatolik yuz berdi",
        loginToSave: "Natijalarni saqlash uchun tizimga kiring"
      }
    },
    applicationSuccess: {
      title: "Ariza Muvaffaqiyatli Topshirildi!",
      thankYou: "Arizangiz uchun rahmat",
      referenceNumber: "Ma'lumotnoma Raqami",
      timeline: "Ariza Jarayoni",
      submitted: "Ariza Topshirildi",
      agencyReview: "Agentlik Ko'rib Chiqmoqda (48 soat)",
      universityDecision: "Universitet Qarori",
      nextStepsDescription: "Arizangiz muvaffaqiyatli topshirildi. Biz sizning arizangizni 48 soat ichida ko'rib chiqamiz va siz bilan bog'lanamiz.",
      step1: "Agentlik sizning arizangizni 48 soat ichida ko'rib chiqadi",
      step2: "Universitet qarorini kutamiz",
      step3: "Siz bilan bog'lanamiz va keyingi qadamlarni aytib beramiz",
      applyAnother: "Boshqa Dasturga Ariza Topshirish"
    },
    programDetail: {
      overview: "Umumiy Ma'lumot",
      requirements: "Talablar",
      deadlines: "Muddatlar",
      costs: "Xarajatlar",
      duration: "Davomiyligi",
      intake: "Qabul",
      language: "Ta'lim Tili",
      startDate: "Boshlanish Sanasi",
      description: "Tavsif",
      academicRequirements: "Akademik Talablar",
      admissionRequirements: "Qabul Talablari",
      minimumGPA: "Minimal GPA",
      languageRequirements: "Til Talablari",
      requiredDocuments: "Zarur Hujjatlar",
      curriculum: "O'quv Rejasi",
      careerProspects: "Karyera Imkoniyatlari",
      quickInformation: "Tezkor Ma'lumot",
      intakeDates: "Qabul Muddatlari",
      applicationDeadline: "Ariza Muddati",
      decisionDate: "Qaror Sanasi",
      tuitionFee: "O'qish Haqi",
      applicationFee: "Ariza Haqi",
      visaFee: "Viza Haqi",
      monthlyLiving: "Oylik Yashash Xarajatlari",
      housingAvailability: "Yotoqxona",
      available: "Mavjud",
      notAvailable: "Mavjud emas",
      totalEstimatedCost: "Jami Taxminiy Xarajat",
      firstYear: "Birinchi Yil",
      managedBy: "Boshqaruvchi",
      verifiedAgency: "Tasdiqlangan Agentlik",
      responseTime: "Javob Vaqti",
      hours: "soat",
      requestHelp: "Yordam So'rash",
      apply: "Ariza Topshirish",
      save: "Saqlash",
      urgentDeadline: "Diqqat",
      daysUntilDeadline: "kun qoldi!",
      backToPrograms: "Dasturlarga qaytish",
      applyNow: "Hozir ariza topshiring",
      saveProgram: "Dasturni saqlash",
      scholarshipAvailable: "Stipendiya mavjud",
      topUniversity: "Eng yaxshi universitet",
      noTuition: "To'lovsiz",
      availableOnCampus: "Kampusda mavjud",
      offCampusOnly: "Faqat kampusdan tashqarida",
      rollingAdmissions: "Doimiy qabul",
      programDescription: "Dastur tavsifi",
      whatYouLearn: "Siz o'rganadigan narsalar",
      careerOutlook: "Martaba istiqboli",
      advantages: "Afzalliklar",
      considerations: "E'tiborga olinishi kerak",
      eligibilityRequirements: "Muvofiqlik talablari",
      languageProficiency: "Til bilish darajasi",
      relatedPrograms: "Tegishli dasturlar",
      costBreakdown: "Xarajatlar taqsimoti",
      tuitionFeePerYear: "O'qish to'lovi (yiliga)",
      housingCostPerMonth: "Yashash xarajati (oyiga)",
      livingCostPerMonth: "Yashash xarajati (oyiga)",
      visaApplicationFee: "Viza uchun to'lov",
      scholarshipOpportunities: "Stipendiya imkoniyatlari mavjud",
      scholarshipDescription: "Ushbu dastur turli xil stipendiya imkoniyatlariga mos keladi va o'qish xarajatlarini kamaytirishi yoki yo'q qilishi mumkin.",
      exploreScholarships: "Stipendiyalarni o'rganing",
      deadlineAlert: "Muddat ogohlantirishi",
      deadlineInDays: "Ariza topshirish muddati {days} kun ichida",
      applySoon: "O'rningizni band qilish uchun tezroq ariza topshiring!",
      missingDocuments: "Hujjatlar yetishmayaptimi?",
      documentHelp: "Bizning hamkor agentliklar barcha kerakli hujjatlarni tayyorlashda va arizangizni to'ldirganligini ta'minlashda yordam beradi.",
      starts: "Boshlanadi",
      applicationOpens: "Ariza qabul qilinadi",
      shortlistNotification: "Qisqa ro'yxat haqida xabar",
      finalDecision: "Yakuniy qaror",
      admissionType: "Qabul turi",
      housing: "Yashash joyi"
    },
    scholarshipDetail: {
      overview: "Umumiy Ma'lumot",
      eligibility: "Shartlar",
      application: "Ariza Tartibi",
      applicationSteps: "Ariza Bosqichlari",
      timeline: "Muddat",
      amount: "Miqdor",
      coverage: "Qamrov",
      country: "Mamlakat",
      field: "Soha",
      keyInfo: "Asosiy Ma'lumot",
      tuitionFees: "O'qish Haqi",
      livingExpenses: "Yashash Xarajatlari",
      travelCosts: "Sayohat Xarajatlari",
      healthInsurance: "Tibbiy Sug'urta",
      booksSupplies: "Kitoblar va Materiallar",
      description: "Tavsif",
      requirements: "Talablar",
      benefits: "Imtiyozlar",
      applicationProcess: "Ariza Jarayoni",
      applicationOpen: "Ariza Ochilishi",
      deadline: "Muddat",
      applicationDeadline: "Ariza Muddati",
      resultsAnnounced: "Natijalar E'lon Qilinishi",
      results: "Natijalar",
      programStarts: "Dastur Boshlanishi",
      apply: "Ariza Topshirish",
      startApplication: "Ariza Boshlash",
      contactCounselor: "Maslahatchi Bilan Aloqa",
      readyToApply: "Arizaga Tayyormisiz?",
      deadlineAlert: "Ariza muddati",
      save: "Saqlash",
      urgentDeadline: "Diqqat",
      daysUntilDeadline: "kun qoldi!"
    },
    careerDetail: {
      overview: "Umumiy Ma'lumot",
      salary: "Ish Haqi",
      skills: "Ko'nikmalar",
      education: "Ta'lim",
      outlook: "Istiqbol",
      description: "Tavsif",
      salaryByRegion: "Mintaqalar Bo'yicha Ish Haqi",
      northAmerica: "Shimoliy Amerika",
      europe: "Yevropa",
      asia: "Osiyo",
      middleEast: "Yaqin Sharq",
      requiredSkills: "Zarur Ko'nikmalar",
      educationPath: "Ta'lim Yo'li",
      recommendedDegree: "Tavsiya Etilgan Daraja",
      relevantFields: "Tegishli Sohalar",
      careerOutlook: "Martaba Istiqboli",
      growthRate: "O'sish Sur'ati",
      nextYears: "keyingi 10 yil",
      jobOpenings: "Ish O'rinlari",
      annually: "yiliga",
      careerProgression: "Martaba Rivojlanishi",
      entryLevel: "Boshlang'ich",
      midLevel: "O'rta",
      seniorLevel: "Yuqori",
      years: "yil",
      prosAndCons: "Afzalliklari va Kamchiliklari",
      pros: "Afzalliklari",
      cons: "Kamchiliklari",
      relatedFields: "Tegishli Sohalar",
      topUniversities: "Eng Yaxshi Universitetlar",
      explorePrograms: "Dasturlarni Ko'rish"
    },
    footer: {
      tagline: "Xorijdagi ta'limga yo'lingiz — oddiy va ishonchli",
      contact: "Aloqa",
      email: "Email",
      phone: "Telefon",
      location: "Manzil",
      programs: "Dasturlar",
      universities: "Universitetlar",
      scholarships: "Stipendiyalar",
      careers: "Martabalar",
      about: "Biz Haqimizda",
      aboutUs: "Kompaniya Haqida",
      ourTeam: "Jamoamiz",
      partners: "Hamkorlar",
      news: "Yangiliklar",
      legal: "Huquqiy",
      privacy: "Maxfiylik Siyosati",
      terms: "Foydalanish Shartlari",
      cookies: "Cookie Siyosati",
      allRightsReserved: "Barcha huquqlar himoyalangan"
    },
    notFound: {
      title: "Sahifa Topilmadi",
      message: "Kechirasiz, siz qidirayotgan sahifa mavjud emas.",
      backHome: "Bosh Sahifaga Qaytish"
    }
  },
  ru: {
    nav: {
      home: "Главная",
      findPrograms: "Программы",
      universities: "Университеты",
      scholarships: "Стипендии",
      careers: "Карьера",
      getSupport: "Поддержка",
      about: "О нас",
      contact: "Контакты",
      blog: "Блог",
      faq: "Вопросы",
      login: "Войти",
      signup: "Регистрация"
    },
    common: {
      all: "Все",
      error: "Ошибка",
      search: "Поиск",
      filters: "Фильтры",
      results: "Результаты",
      viewDetails: "Подробнее",
      apply: "Подать Заявку",
      contactCounselor: "Связаться с Консультантом",
      learnMore: "Узнать Больше",
      back: "Назад",
      next: "Далее",
      previous: "Назад",
      save: "Сохранить",
      cancel: "Отмена",
      completed: "Завершено",
      pending: "Ожидание",
      whatNext: "Что Дальше",
      country: "Страна",
      field: "Область",
      degree: "Степень",
      coverage: "Покрытие",
      amount: "Сумма",
      deadline: "Срок",
      open: "Открыто",
      resultsAnnounced: "Результаты объявлены",
      timeline: "График",
      noResultsTitle: "Ничего не найдено",
      noResultsSubtitle: "Попробуйте изменить параметры поиска",
      searchPlaceholder: "Поиск...",
      loading: "Загрузка...",
      saving: "Сохранение...",
      university: "Университет",
      program: "Программа"
    },
    months: {
      jan: "Янв",
      feb: "Фев",
      mar: "Мар",
      apr: "Апр",
      may: "Май",
      jun: "Июн",
      jul: "Июл",
      aug: "Авг",
      sep: "Сен",
      oct: "Окт",
      nov: "Ноя",
      dec: "Дек"
    },
    hero: {
      title: "Найдите и Поступите в Лучшие Университеты за Рубежом",
      subtitle: "Просто, Быстро, Надёжно — специально для узбекских студентов",
      searchTitle: "Начните поиск университета",
      findUniversity: "Найти Университет",
      country: "Страна",
      selectCountry: "Выберите страну",
      degree: "Степень",
      selectDegree: "Выберите степень",
      chooseDegree: "Выберите степень",
      bachelor: "Бакалавр",
      master: "Магистр",
      phd: "PhD",
      field: "Область",
      selectField: "Выберите область",
      searchPrograms: "Искать Программы",
      searchButton: "Искать Программы",
      quickAccess: "Быстрый Доступ",
      explorePrograms: "Обзор Программ",
      findScholarships: "Найти Стипендии",
      takeCareerQuiz: "Пройти Тест по Карьере"
    },
    values: {
      title: "Почему StudyPath?",
      personalized: "Персонализированный Подбор",
      personalizedDesc: "Программы, соответствующие вашим целям и возможностям",
      verified: "Проверенные Агентства",
      verifiedDesc: "Работайте только с надёжными партнёрами",
      transparent: "Прозрачные Цены",
      transparentDesc: "Точная информация без скрытых платежей",
      scholarships: "Центр Стипендий",
      scholarshipsDesc: "Найдите тысячи грантов и стипендий"
    },
    whyChoose: {
      title: "Почему Стоит Выбрать StudyPath?",
      personalizedMatches: "Персонализированные Совпадения",
      personalizedMatchesDesc: "Найдите программы, соответствующие вашим целям, баллам и бюджету",
      trustedSupport: "Надёжная Поддержка",
      trustedSupportDesc: "Профессиональное руководство через проверенные агентства и консультантов",
      timeSaving: "Экономия Времени",
      timeSavingDesc: "Сравнивайте тысячи программ в одном месте и подавайте заявки онлайн",
      informedDecisions: "Обоснованные Решения",
      informedDecisionsDesc: "Принимайте правильный выбор с помощью подробной информации и отзывов"
    },
    howItWorks: {
      title: "Как Это Работает",
      step1: "Поиск и Фильтр",
      step1Desc: "Найдите подходящие программы",
      step2: "Подать Заявку",
      step2Desc: "Подайте заявку через онлайн-формы",
      step3: "Получить Помощь",
      step3Desc: "Консультанты помогут вам"
    },
    cta: {
      title: "Готовы Начать Свой Путь?",
      description: "Изучите тысячи программ и найдите идеальный университет для вас",
      button: "Обзор Программ"
    },
    programs: {
      title: "Университетские Программы",
      subtitle: "Просмотрите тысячи программ за рубежом",
      pageTitle: "Университетские Программы",
      pageDescription: "Просмотрите тысячи программ за рубежом и найдите подходящее образование",
      search: "Искать программы или университеты...",
      searchPlaceholder: "Искать программы или университеты...",
      filters: "Фильтры",
      studyLevel: "Уровень Обучения",
      allLevels: "Все уровни",
      fieldOfStudy: "Область Обучения",
      allFields: "Все области",
      country: "Страна",
      tuitionRange: "Стоимость Обучения",
      anyRange: "Любая цена",
      free: "Бесплатно",
      showing: "Показано",
      programs: "программ",
      results: "результатов найдено",
      perYear: "/год",
      noTuition: "Бесплатное Обучение",
      scholarship: "Стипендия Доступна",
      scholarshipAvailable: "Стипендия Доступна",
      highDemand: "Высокий Спрос",
      matchScore: "Соответствие",
      deadline: "Срок",
      viewDetails: "Подробнее",
      save: "Сохранить",
      apply: "Подать Заявку",
      askAgency: "Спросить Агентство"
    },
    universities: {
      pageTitle: "Университеты",
      pageDescription: "Просмотрите университеты и программы по странам",
      selectCountry: "Выберите страну",
      allCountries: "Все страны",
      countryOverview: "О Стране",
      tuitionRange: "Стоимость Обучения",
      livingCost: "Расходы на Проживание",
      visaRequirement: "Визовые Требования",
      programsAvailable: "Доступные Программы",
      filterByDegree: "По степени",
      filterByField: "По области",
      filterByTuition: "По цене",
      filterByDeadline: "По сроку",
      requirements: "Требования",
      intakeDates: "Даты Приёма",
      applicationDeadline: "Срок Подачи",
      viewProgram: "Смотреть Программу",
      applyNow: "Подать Заявку",
      perMonth: "/месяц",
      perYear: "/год",
      requiredVisa: "Требуется Виза",
      countries: {
        turkey: "Турция",
        malaysia: "Малайзия",
        qatar: "Катар",
        saudiArabia: "Саудовская Аравия",
        australia: "Австралия",
        uk: "Великобритания",
        canada: "Канада",
        germany: "Германия",
        usa: "США",
        poland: "Польша"
      }
    },
    scholarships: {
      title: "Стипендии",
      subtitle: "Найдите международные гранты и стипендии",
      pageTitle: "Международные Стипендии",
      pageDescription: "Найдите гранты и стипендии для обучения в лучших университетах мира",
      searchPlaceholder: "Искать стипендии...",
      search: "Искать стипендии...",
      filters: "Фильтры",
      filterCountry: "Страна",
      filterField: "Область",
      filterDegree: "Степень",
      filterCoverage: "Покрытие",
      filterDeadline: "Срок",
      deadlineFilter: {
        all: "Все сроки",
        upcoming: "Скоро (30 дней)",
        thisMonth: "В этом месяце",
        next3Months: "В ближайшие 3 месяца",
      },
      results: "результатов найдено",
      fullTuition: "Полная Оплата Обучения",
      partialTuition: "Частичная Оплата",
      livingStipend: "Стипендия на Проживание",
      fullCoverage: "Полное Покрытие",
      partialCoverage: "Частичное Покрытие",
      coverage: "Покрытие",
      amount: "Сумма",
      deadline: "Срок",
      organization: "Организация",
      degreeLevel: "Степень",
      viewDetails: "Подробнее",
      apply: "Подать заявку",
      applyOnOfficialSite: "Подать заявку на официальном сайте",
      save: "Сохранить",
      contactCounselor: "Связаться с Консультантом",
      noResultsTitle: "Ничего не найдено",
      noResultsSubtitle: "Попробуйте изменить параметры поиска",
      daysLeft: "дней осталось",
      closed: "Закрыто",
      lastDay: "Последний день подачи!",
      applicationClosesOn: "Прием заявок закрывается",
      applicationClosed: "Прием заявок на эту стипендию закрыт.",
      infoOutdated: "Информация может быть устаревшей",
      infoNotRecentlyUpdated: "Информация об этой стипендии не обновлялась более 90 дней. Пожалуйста, проверьте детали на официальном сайте.",
      coverageDetails: "Детали покрытия",
      tuitionCoverage: "Покрытие обучения",
      travelAllowance: "Покрытие поездок",
      insuranceCoverage: "Медицинская страховка",
      otherBenefits: "Другие преимущества",
      requiredDocuments: "Необходимые документы",
      commonMistakes: "Распространенные ошибки",
      trustSignals: "Доверие и проверка",
      verifiedScholarship: "Проверенная стипендия",
      officialWebsite: "Официальный сайт",
      relatedPrograms: "Связанные программы",
      relatedCareers: "Связанные карьеры",
      faq: "Часто задаваемые вопросы",
      externalRedirectTitle: "Вы покидаете нашу платформу",
      externalRedirectMessage: "Вы покидаете нашу платформу и будете подавать заявку напрямую на официальном сайте стипендии. Мы не несем ответственности за процесс подачи заявки или результаты.",
      agreeAndContinue: "Я понимаю и согласен продолжить",
      continueToApplication: "Перейти к заявке",
      lastUpdated: "Последнее обновление",
      languageRequirements: "Языковые требования",
      gpaRequirement: "Минимальный средний балл",
      nationalityRestrictions: "Требования к гражданству",
      eligibility: "Требования",
      benefits: "Преимущества",
      applicationProcess: "Процесс подачи",
      timeline: "График",
      keyInfo: "Ключевая информация",
    },
    apply: {
      title: "Подать Заявку",
      subtitle: "Подайте заявку на университетские программы за рубежом",
      applicationForm: "Форма Заявки",
      applyingTo: "Подача Заявки На",
      degreeLevel: "Степень",
      yourCompletedEducation: "Ваше Полученное Образование",
      completedEducationHelp: "Ваше текущее образование (не программа, на которую вы подаете заявку)",
      profileStep: "Профиль",
      eligibilityStep: "Соответствие",
      documentsStep: "Документы",
      reviewStep: "Проверка",
      confirmationStep: "Подтверждение",
      personalDetails: "Личные Данные",
      academicInfo: "Академическая Информация (Необязательно)",
      academicInfoOptional: "Академическая Информация (Необязательно)",
      reviewSubmit: "Проверка и Отправка",
      firstName: "Имя",
      lastName: "Фамилия",
      email: "Email",
      phone: "Телефон",
      countryOfResidence: "Страна Проживания",
      selectCountry: "Выберите страну",
      city: "Город",
      selectCity: "Выберите город",
      selectCountryFirst: "Сначала выберите страну",
      gender: "Пол",
      selectGender: "Выберите",
      selectDate: "Выберите дату",
      male: "Мужской",
      female: "Женский",
      other: "Другой",
      dateOfBirth: "Дата Рождения",
      dateOfBirthOptional: "Дата Рождения (Необязательно)",
      currentEducationLevel: "Текущий Уровень Образования",
      gpa: "Средний Балл",
      englishTest: "Тест по Английскому",
      englishScore: "Балл Теста",
      uploadTranscript: "Загрузить Транскрипт (Необязательно)",
      consentText: "Я подтверждаю правильность моих данных",
      programUniversity: "Программа + Университет",
      notProvided: "Не указано",
      requiredField: "Это поле обязательно",
      invalidEmail: "Введите правильный email",
      invalidPhone: "Введите правильный телефон",
      consentRequired: "Требуется согласие",
      fillRequired: "Заполните все обязательные поля",
      submitting: "Отправка...",
      submit: "Подать Заявку",
      readyToSubmit: "Готово к отправке!"
    },
    applicationSuccess: {
      title: "Заявка Успешно Отправлена!",
      thankYou: "Спасибо за вашу заявку",
      referenceNumber: "Номер Заявки",
      timeline: "Процесс Заявки",
      submitted: "Заявка Отправлена",
      agencyReview: "Проверка Агентством (48 часов)",
      universityDecision: "Решение Университета",
      nextStepsDescription: "Ваша заявка успешно отправлена. Мы рассмотрим вашу заявку в течение 48 часов и свяжемся с вами.",
      step1: "Агентство рассмотрит вашу заявку в течение 48 часов",
      step2: "Ожидаем решение университета",
      step3: "Мы свяжемся с вами и сообщим о следующих шагах",
      applyAnother: "Подать Заявку на Другую Программу"
    },
    requestHelp: {
      title: "Запросить помощь с заявкой",
      subtitle: "Наша команда свяжется с вами в течение 24-48 часов",
      fullName: "Полное имя",
      email: "Email адрес",
      phone: "Номер телефона (необязательно)",
      helpType: "В чём вам нужна помощь?",
      helpTypes: {
        eligibility: "Вопросы соответствия",
        documents: "Требования к документам",
        application: "Процесс подачи заявки",
        general: "Общий запрос"
      },
      educationLevel: "Текущий уровень образования",
      educationLevels: {
        highSchool: "Средняя школа",
        bachelor: "Степень бакалавра",
        master: "Степень магистра"
      },
      message: "Опишите ваш вопрос или проблему",
      messagePlaceholder: "Пожалуйста, предоставьте подробности о том, в чём вам нужна помощь...",
      contactMethod: "Предпочтительный способ связи",
      contactMethods: {
        email: "Email",
        phone: "Телефонный звонок",
        whatsapp: "WhatsApp"
      },
      submit: "Отправить запрос",
      cancel: "Отмена",
      successTitle: "Запрос отправлен!",
      successMessage: "Наша команда свяжется с вами в течение 24-48 часов предпочтительным способом.",
      loginRequired: "Пожалуйста, войдите, чтобы запросить помощь",
      loginButton: "Войти"
    },
    savedPrograms: {
      title: "Сохранённые программы",
      empty: "Вы ещё не сохранили ни одной программы",
      emptyDescription: "Просмотрите программы и нажмите 'Сохранить программу', чтобы добавить их сюда",
      browsePrograms: "Просмотр программ",
      saved: "Сохранено",
      saveProgram: "Сохранить программу",
      unsave: "Удалить",
      addNote: "Добавить заметку",
      notePlaceholder: "Добавьте личные заметки об этой программе...",
      compareSelected: "Сравнить выбранные",
      selectToCompare: "Выберите 2+ программы для сравнения",
      loginToSave: "Пожалуйста, войдите, чтобы сохранять программы",
      savedSuccess: "Программа успешно сохранена",
      unsavedSuccess: "Программа удалена из сохранённых",
      compare: {
        title: "Сравнить программы",
        backToSaved: "Назад к сохранённым программам",
        university: "Университет",
        program: "Программа",
        country: "Страна",
        degree: "Уровень степени",
        field: "Область обучения",
        tuition: "Стоимость обучения",
        applicationFee: "Регистрационный сбор",
        duration: "Продолжительность",
        housing: "Жильё доступно",
        requirements: "Требования",
        deadlines: "Сроки подачи заявок",
        applyNow: "Подать заявку сейчас"
      }
    },
    agencyDashboard: {
      title: "Панель Управления Агентства",
      subtitle: "Управление запросами на помощь и работа со студентами",
      totalRequests: "Всего Запросов",
      allRequests: "Все запросы",
      pending: "Ожидают",
      needsResponse: "Требуют ответа",
      inProgress: "В Работе",
      activeWork: "Активная работа",
      resolved: "Решено",
      completed: "Завершено",
      filters: "Фильтры",
      searchPlaceholder: "Поиск по имени, email, университету или программе...",
      allStatuses: "Все статусы",
      statusPending: "Ожидает",
      statusInProgress: "В работе",
      statusResolved: "Решено",
      statusClosed: "Закрыто",
      helpRequests: "Запросы на Помощь",
      helpRequestsDescription: "Управляйте всеми запросами на помощь студентам",
      viewDetails: "Подробнее",
      noRequests: "Запросов не найдено",
      noRequestsDescription: "Пока нет запросов на помощь",
      requestDetails: "Детали Запроса",
      requestDetailsDescription: "Полная информация и обновления статуса",
      studentInfo: "Информация о Студенте",
      programInfo: "Информация о Программе",
      studentMessage: "Сообщение Студента",
      updateStatus: "Обновить Статус",
      agencyNotes: "Заметки Агентства",
      agencyNotesPlaceholder: "Введите внутренние заметки по этому запросу...",
      createdAt: "Создано",
      updatedAt: "Обновлено",
      saveChanges: "Сохранить Изменения",
      updateSuccess: "Запрос успешно обновлён",
      updateError: "Ошибка при обновлении запроса"
    },
    careers: {
      title: "Карьерный Советник",
      subtitle: "Найдите и спланируйте своё будущее",
      pageTitle: "Карьерный Советник",
      pageDescription: "Спланируйте своё будущее и найдите наиболее подходящий карьерный путь",
      searchTab: "Поиск Карьеры",
      quizTab: "Карьерный Тест",
      searchPlaceholder: "Искать карьеры...",
      search: "Искать карьеры...",
      results: "результатов найдено",
      salary: "Зарплата",
      growth: "Рост",
      demand: "Спрос",
      demandVeryHigh: "Очень Высокий",
      demandHigh: "Высокий",
      demandModerate: "Средний",
      skills: "Необходимые Навыки",
      relatedFields: "Связанные Области",
      topUniversities: "Лучшие Университеты",
      pros: "Преимущества",
      cons: "Недостатки",
      viewDetails: "Подробнее",
      learnMore: "Узнать Больше",
      explorePrograms: "Обзор Программ",
      question: "Вопрос",
      next: "Далее",
      previous: "Назад",
      seeResults: "Посмотреть Результаты",
      recommendedCareers: "Рекомендуемые Карьеры",
      quiz: {
        title: "Тест на Профориентацию по RIASEC",
        subtitle: "Ответьте на 12 вопросов, и мы подберём подходящие карьеры",
        score: "Балл",
        resultsTitle: "Ваши Лучшие Карьерные Совпадения",
        resultsSubtitle: "На основе вашего типа личности по методике Холланда",
        yourType: "Ваш тип",
        personalityProfile: "Профиль Личности",
        primary: "Основной",
        match: "совпадение",
        retake: "Пройти Заново",
        saveResults: "Сохранить Результаты",
        saved: "Сохранено",
        saveSuccess: "Ваши результаты успешно сохранены",
        saveError: "Ошибка при сохранении результатов",
        loginToSave: "Войдите, чтобы сохранить результаты"
      }
    },
    programDetail: {
      overview: "Обзор",
      requirements: "Требования",
      deadlines: "Сроки",
      costs: "Расходы",
      duration: "Продолжительность",
      intake: "Прием",
      language: "Язык Обучения",
      startDate: "Дата Начала",
      description: "Описание",
      academicRequirements: "Академические Требования",
      admissionRequirements: "Требования к Поступлению",
      minimumGPA: "Минимальный GPA",
      languageRequirements: "Языковые Требования",
      requiredDocuments: "Необходимые Документы",
      curriculum: "Учебная Программа",
      careerProspects: "Карьерные Перспективы",
      quickInformation: "Краткая Информация",
      intakeDates: "Даты Приёма",
      applicationDeadline: "Срок Подачи Заявки",
      decisionDate: "Дата Решения",
      tuitionFee: "Плата за Обучение",
      applicationFee: "Плата за Заявку",
      visaFee: "Визовый Сбор",
      monthlyLiving: "Ежемесячные Расходы на Проживание",
      housingAvailability: "Общежитие",
      available: "Доступно",
      notAvailable: "Недоступно",
      totalEstimatedCost: "Общая Ориентировочная Стоимость",
      firstYear: "Первый Год",
      managedBy: "Управляется",
      verifiedAgency: "Проверенное Агентство",
      responseTime: "Время Ответа",
      hours: "часов",
      requestHelp: "Запросить Помощь",
      apply: "Подать Заявку",
      save: "Сохранить",
      urgentDeadline: "Внимание",
      daysUntilDeadline: "дней осталось!",
      backToPrograms: "Назад к программам",
      applyNow: "Подать заявку",
      saveProgram: "Сохранить программу",
      scholarshipAvailable: "Стипендия доступна",
      topUniversity: "Топ университет",
      noTuition: "Без оплаты",
      availableOnCampus: "Доступно в кампусе",
      offCampusOnly: "Только вне кампуса",
      rollingAdmissions: "Прием на постоянной основе",
      programDescription: "Описание программы",
      whatYouLearn: "Что вы изучите",
      careerOutlook: "Карьерные перспективы",
      advantages: "Преимущества",
      considerations: "Что учесть",
      eligibilityRequirements: "Требования к участию",
      languageProficiency: "Владение языком",
      relatedPrograms: "Связанные программы",
      costBreakdown: "Разбивка расходов",
      tuitionFeePerYear: "Плата за обучение (в год)",
      housingCostPerMonth: "Стоимость жилья (в месяц)",
      livingCostPerMonth: "Расходы на жизнь (в месяц)",
      visaApplicationFee: "Стоимость визы",
      scholarshipOpportunities: "Доступны возможности стипендий",
      scholarshipDescription: "Эта программа подходит для различных стипендиальных возможностей, которые могут помочь сократить или устранить расходы на обучение.",
      exploreScholarships: "Изучить стипендии",
      deadlineAlert: "Уведомление о сроке",
      deadlineInDays: "Срок подачи заявки через {days} дней",
      applySoon: "Подавайте заявку скорее, чтобы обеспечить себе место!",
      missingDocuments: "Отсутствуют документы?",
      documentHelp: "Наши партнерские агентства помогут подготовить все необходимые документы и убедиться, что ваша заявка полная.",
      starts: "Начало",
      applicationOpens: "Прием заявок открыт",
      shortlistNotification: "Уведомление о шорт-листе",
      finalDecision: "Окончательное решение",
      admissionType: "Тип приема",
      housing: "Жилье"
    },
    scholarshipDetail: {
      overview: "Обзор",
      eligibility: "Условия",
      application: "Процесс Подачи",
      applicationSteps: "Этапы Подачи",
      timeline: "График",
      amount: "Сумма",
      coverage: "Покрытие",
      country: "Страна",
      field: "Область",
      keyInfo: "Ключевая Информация",
      tuitionFees: "Плата за Обучение",
      livingExpenses: "Расходы на Проживание",
      travelCosts: "Транспортные Расходы",
      healthInsurance: "Медицинская Страховка",
      booksSupplies: "Книги и Материалы",
      description: "Описание",
      requirements: "Требования",
      benefits: "Преимущества",
      applicationProcess: "Процесс Подачи",
      applicationOpen: "Открытие Заявок",
      deadline: "Срок",
      applicationDeadline: "Срок Подачи",
      resultsAnnounced: "Объявление Результатов",
      results: "Результаты",
      programStarts: "Начало Программы",
      apply: "Подать Заявку",
      startApplication: "Начать Подачу",
      contactCounselor: "Связаться с Консультантом",
      readyToApply: "Готовы Подать Заявку?",
      deadlineAlert: "Срок подачи заявки",
      save: "Сохранить",
      urgentDeadline: "Внимание",
      daysUntilDeadline: "дней осталось!"
    },
    careerDetail: {
      overview: "Обзор",
      salary: "Зарплата",
      skills: "Навыки",
      education: "Образование",
      outlook: "Перспективы",
      description: "Описание",
      salaryByRegion: "Зарплата по Регионам",
      northAmerica: "Северная Америка",
      europe: "Европа",
      asia: "Азия",
      middleEast: "Ближний Восток",
      requiredSkills: "Необходимые Навыки",
      educationPath: "Путь Образования",
      recommendedDegree: "Рекомендуемая Степень",
      relevantFields: "Связанные Области",
      careerOutlook: "Карьерные Перспективы",
      growthRate: "Темп Роста",
      nextYears: "следующие 10 лет",
      jobOpenings: "Вакансии",
      annually: "ежегодно",
      careerProgression: "Карьерный Рост",
      entryLevel: "Начальный",
      midLevel: "Средний",
      seniorLevel: "Старший",
      years: "лет",
      prosAndCons: "Плюсы и Минусы",
      pros: "Плюсы",
      cons: "Минусы",
      relatedFields: "Связанные Области",
      topUniversities: "Лучшие Университеты",
      explorePrograms: "Обзор Программ"
    },
    footer: {
      tagline: "Ваш путь к образованию за рубежом — просто и надёжно",
      contact: "Контакты",
      email: "Email",
      phone: "Телефон",
      location: "Адрес",
      programs: "Программы",
      universities: "Университеты",
      scholarships: "Стипендии",
      careers: "Карьера",
      about: "О Нас",
      aboutUs: "О Компании",
      ourTeam: "Наша Команда",
      partners: "Партнёры",
      news: "Новости",
      legal: "Правовая Информация",
      privacy: "Политика Конфиденциальности",
      terms: "Условия Использования",
      cookies: "Политика Cookie",
      allRightsReserved: "Все права защищены"
    },
    notFound: {
      title: "Страница не найдена",
      message: "К сожалению, страница, которую вы ищете, не существует.",
      backHome: "Вернуться на Главную"
    }
  },
  en: {
    nav: {
      home: "Home",
      findPrograms: "Programs",
      universities: "Universities",
      scholarships: "Scholarships",
      careers: "Careers",
      getSupport: "Support",
      about: "About",
      contact: "Contact",
      blog: "Blog",
      faq: "FAQ",
      login: "Log In",
      signup: "Sign Up"
    },
    common: {
      all: "All",
      error: "Error",
      search: "Search",
      filters: "Filters",
      results: "Results",
      viewDetails: "View Details",
      apply: "Apply",
      contactCounselor: "Contact Counselor",
      learnMore: "Learn More",
      back: "Back",
      next: "Next",
      previous: "Previous",
      save: "Save",
      cancel: "Cancel",
      completed: "Completed",
      pending: "Pending",
      whatNext: "What's Next",
      country: "Country",
      field: "Field",
      degree: "Degree",
      coverage: "Coverage",
      amount: "Amount",
      deadline: "Deadline",
      open: "Open",
      resultsAnnounced: "Results Announced",
      timeline: "Timeline",
      noResultsTitle: "No results found",
      noResultsSubtitle: "Try adjusting your search criteria",
      searchPlaceholder: "Search...",
      loading: "Loading...",
      saving: "Saving...",
      university: "University",
      program: "Program"
    },
    months: {
      jan: "Jan",
      feb: "Feb",
      mar: "Mar",
      apr: "Apr",
      may: "May",
      jun: "Jun",
      jul: "Jul",
      aug: "Aug",
      sep: "Sep",
      oct: "Oct",
      nov: "Nov",
      dec: "Dec"
    },
    hero: {
      title: "Find and Apply to Top Universities Abroad",
      subtitle: "Simple, Fast, Trusted — tailored for Uzbek students",
      searchTitle: "Start your university search",
      findUniversity: "Find University",
      country: "Country",
      selectCountry: "Select country",
      degree: "Degree",
      selectDegree: "Select degree",
      chooseDegree: "Choose degree",
      bachelor: "Bachelor",
      master: "Master",
      phd: "PhD",
      field: "Field",
      selectField: "Select field",
      searchPrograms: "Search Programs",
      searchButton: "Search Programs",
      quickAccess: "Quick Access",
      explorePrograms: "Explore Programs",
      findScholarships: "Find Scholarships",
      takeCareerQuiz: "Take Career Quiz"
    },
    values: {
      title: "Why StudyPath?",
      personalized: "Personalized Matches",
      personalizedDesc: "Programs tailored to your goals and abilities",
      verified: "Verified Agencies",
      verifiedDesc: "Work only with trusted partners",
      transparent: "Transparent Costs",
      transparentDesc: "Clear information with no hidden fees",
      scholarships: "Scholarship Hub",
      scholarshipsDesc: "Find thousands of grants and scholarships"
    },
    whyChoose: {
      title: "Why Choose StudyPath?",
      personalizedMatches: "Personalized Matches",
      personalizedMatchesDesc: "Find programs that match your goals, grades, and budget",
      trustedSupport: "Trusted Support",
      trustedSupportDesc: "Professional guidance through verified agencies and counselors",
      timeSaving: "Time Saving",
      timeSavingDesc: "Compare thousands of programs in one place and apply online",
      informedDecisions: "Informed Decisions",
      informedDecisionsDesc: "Make the right choice with detailed information and reviews"
    },
    howItWorks: {
      title: "How It Works",
      step1: "Search & Filter",
      step1Desc: "Find programs that match your needs",
      step2: "Apply",
      step2Desc: "Submit applications through online forms",
      step3: "Get Help",
      step3Desc: "Counselors will assist you"
    },
    cta: {
      title: "Ready to Start Your Journey?",
      description: "Explore thousands of programs and find the perfect university for you",
      button: "Explore Programs"
    },
    programs: {
      title: "University Programs",
      subtitle: "Browse thousands of programs abroad",
      pageTitle: "University Programs",
      pageDescription: "Browse thousands of programs abroad and find your perfect education match",
      search: "Search programs or universities...",
      searchPlaceholder: "Search programs or universities...",
      filters: "Filters",
      studyLevel: "Study Level",
      allLevels: "All levels",
      fieldOfStudy: "Field of Study",
      allFields: "All fields",
      country: "Country",
      tuitionRange: "Tuition Range",
      anyRange: "Any price",
      free: "Free",
      showing: "Showing",
      programs: "programs",
      results: "results found",
      perYear: "/year",
      noTuition: "No Tuition",
      scholarship: "Scholarship Available",
      scholarshipAvailable: "Scholarship Available",
      highDemand: "High Demand",
      matchScore: "Match Score",
      deadline: "Deadline",
      viewDetails: "View Details",
      save: "Save",
      apply: "Apply",
      askAgency: "Ask Agency"
    },
    universities: {
      pageTitle: "Universities",
      pageDescription: "Browse universities and programs by country",
      selectCountry: "Select Country",
      allCountries: "All Countries",
      countryOverview: "Country Overview",
      tuitionRange: "Tuition Range",
      livingCost: "Living Cost",
      visaRequirement: "Visa Requirement",
      programsAvailable: "Programs Available",
      filterByDegree: "By Degree",
      filterByField: "By Field",
      filterByTuition: "By Tuition",
      filterByDeadline: "By Deadline",
      requirements: "Requirements",
      intakeDates: "Intake Dates",
      applicationDeadline: "Application Deadline",
      viewProgram: "View Program",
      applyNow: "Apply Now",
      perMonth: "/month",
      perYear: "/year",
      requiredVisa: "Visa Required",
      countries: {
        turkey: "Turkey",
        malaysia: "Malaysia",
        qatar: "Qatar",
        saudiArabia: "Saudi Arabia",
        australia: "Australia",
        uk: "United Kingdom",
        canada: "Canada",
        germany: "Germany",
        usa: "United States",
        poland: "Poland"
      }
    },
    scholarships: {
      title: "Scholarships",
      subtitle: "Find international grants and scholarships",
      pageTitle: "International Scholarships",
      pageDescription: "Find grants and scholarships to study at the world's best universities",
      searchPlaceholder: "Search scholarships...",
      search: "Search scholarships...",
      filters: "Filters",
      filterCountry: "Country",
      filterField: "Field",
      filterDegree: "Degree",
      filterCoverage: "Coverage",
      filterDeadline: "Deadline",
      deadlineFilter: {
        all: "All Deadlines",
        upcoming: "Upcoming (30 days)",
        thisMonth: "This Month",
        next3Months: "Next 3 Months",
      },
      results: "results found",
      fullTuition: "Full Tuition",
      partialTuition: "Partial Tuition",
      livingStipend: "Living Stipend",
      fullCoverage: "Full Coverage",
      partialCoverage: "Partial Coverage",
      coverage: "Coverage",
      amount: "Amount",
      deadline: "Deadline",
      organization: "Organization",
      degreeLevel: "Degree Level",
      viewDetails: "View Details",
      apply: "Apply",
      applyOnOfficialSite: "Apply on Official Website",
      save: "Save",
      contactCounselor: "Contact Counselor",
      noResultsTitle: "No results found",
      noResultsSubtitle: "Try adjusting your search criteria",
      daysLeft: "days left",
      closed: "Closed",
      lastDay: "Last day to apply!",
      applicationClosesOn: "Application closes on",
      applicationClosed: "This scholarship application has closed.",
      infoOutdated: "Info may be outdated",
      infoNotRecentlyUpdated: "This scholarship information hasn't been updated in 90+ days. Please verify details on the official website.",
      coverageDetails: "Coverage Details",
      tuitionCoverage: "Tuition Coverage",
      travelAllowance: "Travel Allowance",
      insuranceCoverage: "Insurance Coverage",
      otherBenefits: "Other Benefits",
      requiredDocuments: "Required Documents",
      commonMistakes: "Common Application Mistakes",
      trustSignals: "Trust & Verification",
      verifiedScholarship: "Verified Scholarship",
      officialWebsite: "Official Website",
      relatedPrograms: "Related Programs",
      relatedCareers: "Related Career Paths",
      faq: "Frequently Asked Questions",
      externalRedirectTitle: "Leaving Our Platform",
      externalRedirectMessage: "You are leaving our platform and will apply directly on the official scholarship website. We are not responsible for the application process or results.",
      agreeAndContinue: "I understand and agree to proceed",
      continueToApplication: "Continue to Application",
      lastUpdated: "Last Updated",
      languageRequirements: "Language Requirements",
      gpaRequirement: "Minimum GPA",
      nationalityRestrictions: "Nationality Restrictions",
      eligibility: "Eligibility",
      benefits: "Benefits",
      applicationProcess: "Application Process",
      timeline: "Timeline",
      keyInfo: "Key Information",
    },
    apply: {
      title: "Apply Now",
      subtitle: "Apply for study abroad programs",
      applicationForm: "Application Form",
      applyingTo: "Applying To",
      degreeLevel: "Degree Level",
      yourCompletedEducation: "Your Highest Completed Education",
      completedEducationHelp: "Your current education background (not the degree you're applying to)",
      personalDetails: "Personal Details",
      academicInfo: "Academic Info (Optional)",
      academicInfoOptional: "Academic Info (Optional)",
      reviewSubmit: "Review & Submit",
      firstName: "First Name",
      lastName: "Last Name",
      email: "Email Address",
      phone: "Phone Number",
      countryOfResidence: "Country of Residence",
      selectCountry: "Select Country",
      city: "City",
      selectCity: "Select City",
      selectCountryFirst: "Please select a country first",
      gender: "Gender",
      selectGender: "Select Gender",
      selectDate: "Select date",
      male: "Male",
      female: "Female",
      other: "Other",
      dateOfBirth: "Date of Birth",
      dateOfBirthOptional: "Date of Birth (Optional)",
      currentEducationLevel: "Current Education Level",
      gpa: "GPA / Average Score",
      englishTest: "English Proficiency Test",
      englishScore: "Test Score",
      uploadTranscript: "Upload Transcript (Optional)",
      consentText: "I confirm my information is accurate",
      programUniversity: "Program + University",
      applicationSummary: "Application Summary",
      editDetails: "Edit Details",
      notProvided: "Not provided",
      requiredField: "This field is required",
      invalidEmail: "Please enter a valid email",
      invalidPhone: "Please enter a valid phone number",
      consentRequired: "You must consent before submitting",
      fillRequired: "Please fill all required fields",
      submitting: "Submitting...",
      submit: "Submit Application",
      readyToSubmit: "Ready to submit!"
    },
    applicationSuccess: {
      title: "Application Submitted Successfully!",
      thankYou: "Thank you for your application",
      referenceNumber: "Reference Number",
      timeline: "Application Timeline",
      submitted: "Application Submitted",
      agencyReview: "Agency Review (48 hours)",
      universityDecision: "University Decision",
      nextStepsDescription: "Your application has been successfully submitted. We will review your application within 48 hours and contact you.",
      step1: "Agency will review your application within 48 hours",
      step2: "Awaiting university decision",
      step3: "We will contact you and inform you of the next steps",
      applyAnother: "Apply to Another Program"
    },
    requestHelp: {
      title: "Request Help with Application",
      subtitle: "Our team will contact you within 24-48 hours",
      fullName: "Full Name",
      email: "Email Address",
      phone: "Phone Number (Optional)",
      helpType: "What do you need help with?",
      helpTypes: {
        eligibility: "Eligibility Questions",
        documents: "Document Requirements",
        application: "Application Process",
        general: "General Inquiry"
      },
      educationLevel: "Current Education Level",
      educationLevels: {
        highSchool: "High School",
        bachelor: "Bachelor's Degree",
        master: "Master's Degree"
      },
      message: "Describe your question or concern",
      messagePlaceholder: "Please provide details about what you need help with...",
      contactMethod: "Preferred Contact Method",
      contactMethods: {
        email: "Email",
        phone: "Phone Call",
        whatsapp: "WhatsApp"
      },
      submit: "Submit Request",
      cancel: "Cancel",
      successTitle: "Request Submitted!",
      successMessage: "Our team will contact you within 24-48 hours via your preferred method.",
      loginRequired: "Please sign in to request help",
      loginButton: "Sign In"
    },
    savedPrograms: {
      title: "Saved Programs",
      empty: "You haven't saved any programs yet",
      emptyDescription: "Browse programs and click 'Save Program' to add them here",
      browsePrograms: "Browse Programs",
      saved: "Saved",
      saveProgram: "Save Program",
      unsave: "Remove",
      addNote: "Add Note",
      notePlaceholder: "Add personal notes about this program...",
      compareSelected: "Compare Selected",
      selectToCompare: "Select 2+ programs to compare",
      loginToSave: "Please sign in to save programs",
      savedSuccess: "Program saved successfully",
      unsavedSuccess: "Program removed from saved list",
      compare: {
        title: "Compare Programs",
        backToSaved: "Back to Saved Programs",
        university: "University",
        program: "Program",
        country: "Country",
        degree: "Degree Level",
        field: "Field of Study",
        tuition: "Tuition",
        applicationFee: "Application Fee",
        duration: "Duration",
        housing: "Housing Available",
        requirements: "Requirements",
        deadlines: "Application Deadlines",
        applyNow: "Apply Now"
      }
    },
    agencyDashboard: {
      title: "Agency Dashboard",
      subtitle: "Manage help requests and work with students",
      totalRequests: "Total Requests",
      allRequests: "All requests",
      pending: "Pending",
      needsResponse: "Needs response",
      inProgress: "In Progress",
      activeWork: "Active work",
      resolved: "Resolved",
      completed: "Completed",
      filters: "Filters",
      searchPlaceholder: "Search by name, email, university or program...",
      allStatuses: "All statuses",
      statusPending: "Pending",
      statusInProgress: "In Progress",
      statusResolved: "Resolved",
      statusClosed: "Closed",
      helpRequests: "Help Requests",
      helpRequestsDescription: "Manage all requests to help students",
      viewDetails: "View Details",
      noRequests: "No Requests Found",
      noRequestsDescription: "There are no help requests at the moment",
      requestDetails: "Request Details",
      requestDetailsDescription: "Full information and status updates",
      studentInfo: "Student Information",
      programInfo: "Program Information",
      studentMessage: "Student Message",
      updateStatus: "Update Status",
      agencyNotes: "Agency Notes",
      agencyNotesPlaceholder: "Enter internal notes about this request...",
      createdAt: "Created",
      updatedAt: "Updated",
      saveChanges: "Save Changes",
      updateSuccess: "Request updated successfully",
      updateError: "Error updating request"
    },
    careers: {
      title: "Career Advisor",
      subtitle: "Discover and plan your future",
      pageTitle: "Career Advisor",
      pageDescription: "Plan your future and find the most suitable career path",
      searchTab: "Search Careers",
      quizTab: "Career Quiz",
      searchPlaceholder: "Search careers...",
      search: "Search careers...",
      results: "results found",
      salary: "Salary",
      growth: "Growth",
      demand: "Demand",
      demandVeryHigh: "Very High",
      demandHigh: "High",
      demandModerate: "Moderate",
      skills: "Required Skills",
      relatedFields: "Related Fields",
      topUniversities: "Top Universities",
      pros: "Pros",
      cons: "Cons",
      viewDetails: "View Details",
      learnMore: "Learn More",
      explorePrograms: "Explore Programs",
      question: "Question",
      next: "Next",
      previous: "Previous",
      seeResults: "See Results",
      recommendedCareers: "Recommended Careers",
      quiz: {
        title: "Holland RIASEC Career Quiz",
        subtitle: "Answer 12 questions to discover your ideal career matches",
        score: "Score",
        resultsTitle: "Your Top Career Matches",
        resultsSubtitle: "Based on your Holland personality type",
        yourType: "Your type",
        personalityProfile: "Personality Profile",
        primary: "Primary",
        match: "match",
        retake: "Retake Quiz",
        saveResults: "Save Results",
        saved: "Saved",
        saveSuccess: "Your results have been saved successfully",
        saveError: "Error saving results",
        loginToSave: "Sign in to save your results"
      }
    },
    programDetail: {
      overview: "Overview",
      requirements: "Requirements",
      deadlines: "Deadlines",
      costs: "Costs",
      duration: "Duration",
      intake: "Intake",
      language: "Language of Instruction",
      startDate: "Start Date",
      description: "Description",
      academicRequirements: "Academic Requirements",
      admissionRequirements: "Admission Requirements",
      minimumGPA: "Minimum GPA",
      languageRequirements: "Language Requirements",
      requiredDocuments: "Required Documents",
      curriculum: "Curriculum",
      careerProspects: "Career Prospects",
      quickInformation: "Quick Information",
      intakeDates: "Intake Dates",
      applicationDeadline: "Application Deadline",
      decisionDate: "Decision Date",
      tuitionFee: "Tuition Fee",
      applicationFee: "Application Fee",
      visaFee: "Visa Fee",
      monthlyLiving: "Monthly Living Costs",
      housingAvailability: "Housing",
      available: "Available",
      notAvailable: "Not Available",
      totalEstimatedCost: "Total Estimated Cost",
      firstYear: "First Year",
      managedBy: "Managed By",
      verifiedAgency: "Verified Agency",
      responseTime: "Response Time",
      hours: "hours",
      requestHelp: "Request Help",
      apply: "Apply",
      save: "Save",
      urgentDeadline: "Attention",
      daysUntilDeadline: "days left!"
    },
    scholarshipDetail: {
      overview: "Overview",
      eligibility: "Eligibility",
      application: "Application",
      applicationSteps: "Application Steps",
      timeline: "Timeline",
      amount: "Amount",
      coverage: "Coverage",
      country: "Country",
      field: "Field",
      keyInfo: "Key Information",
      tuitionFees: "Tuition Fees",
      livingExpenses: "Living Expenses",
      travelCosts: "Travel Costs",
      healthInsurance: "Health Insurance",
      booksSupplies: "Books & Supplies",
      description: "Description",
      requirements: "Requirements",
      benefits: "Benefits",
      applicationProcess: "Application Process",
      applicationOpen: "Application Opens",
      deadline: "Deadline",
      applicationDeadline: "Application Deadline",
      resultsAnnounced: "Results Announced",
      results: "Results",
      programStarts: "Program Starts",
      apply: "Apply",
      startApplication: "Start Application",
      contactCounselor: "Contact Counselor",
      readyToApply: "Ready to Apply?",
      deadlineAlert: "Application deadline",
      save: "Save",
      urgentDeadline: "Attention",
      daysUntilDeadline: "days left!"
    },
    careerDetail: {
      overview: "Overview",
      salary: "Salary",
      skills: "Skills",
      education: "Education",
      outlook: "Outlook",
      description: "Description",
      salaryByRegion: "Salary by Region",
      northAmerica: "North America",
      europe: "Europe",
      asia: "Asia",
      middleEast: "Middle East",
      requiredSkills: "Required Skills",
      educationPath: "Education Path",
      recommendedDegree: "Recommended Degree",
      relevantFields: "Relevant Fields",
      careerOutlook: "Career Outlook",
      growthRate: "Growth Rate",
      nextYears: "next 10 years",
      jobOpenings: "Job Openings",
      annually: "annually",
      careerProgression: "Career Progression",
      entryLevel: "Entry Level",
      midLevel: "Mid Level",
      seniorLevel: "Senior Level",
      years: "years",
      prosAndCons: "Pros & Cons",
      pros: "Pros",
      cons: "Cons",
      relatedFields: "Related Fields",
      topUniversities: "Top Universities",
      explorePrograms: "Explore Programs"
    },
    footer: {
      tagline: "Your path to education abroad — simple and reliable",
      contact: "Contact",
      email: "Email",
      phone: "Phone",
      location: "Location",
      programs: "Programs",
      universities: "Universities",
      scholarships: "Scholarships",
      careers: "Careers",
      about: "About",
      aboutUs: "About Us",
      ourTeam: "Our Team",
      partners: "Partners",
      news: "News",
      legal: "Legal",
      privacy: "Privacy Policy",
      terms: "Terms of Service",
      cookies: "Cookie Policy",
      allRightsReserved: "All rights reserved"
    },
    notFound: {
      title: "Page Not Found",
      message: "Sorry, the page you are looking for does not exist.",
      backHome: "Back to Home"
    }
  }
};
